# generated by datamodel-codegen:
#   filename:  https://codeberg.org/PaZuFa/parlamentszusammenfasser/raw/tag/v0.2.6+v0.0.7/openapi.yml

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class ApiKeyStatus(BaseModel):
    expires_at: Annotated[
        AwareDatetime,
        Field(
            description="When this key will expire. If `is_being_rotated` is true, this is the date the rotation is complete."
        ),
    ]
    is_being_rotated: Annotated[
        bool, Field(description="Whether this key is currently in a transition process")
    ]
    scope: Annotated[
        str,
        Field(
            description="Note: inline enums are not fully supported by openapi-generator"
        ),
    ]


class Autor(BaseModel):
    fachgebiet: str | None = None
    lobbyregister: AnyUrl | None = None
    organisation: str
    person: str | None = None


class CreateApiKey(BaseModel):
    expires_at: Annotated[
        AwareDatetime | None, Field(description="The expiration date of the API Key")
    ] = None
    scope: Annotated[
        str,
        Field(
            description="Note: inline enums are not fully supported by openapi-generator"
        ),
    ]


class Doktyp(StrEnum):
    eckpunktepapier = "eckpunktepapier"
    preparl_entwurf = "preparl-entwurf"
    entwurf = "entwurf"
    antrag = "antrag"
    anfrage = "anfrage"
    antwort = "antwort"
    mitteilung = "mitteilung"
    beschlussempf = "beschlussempf"
    stellungnahme = "stellungnahme"
    gutachten = "gutachten"
    redeprotokoll = "redeprotokoll"
    tops = "tops"
    tops_aend = "tops-aend"
    tops_ergz = "tops-ergz"
    gesetz = "gesetz"
    sonstig = "sonstig"


class DokumentFormat(StrEnum):
    ftm = "ftm"
    pazufa = "pazufa"


class EnumerationNames(StrEnum):
    schlagworte = "schlagworte"
    stationstypen = "stationstypen"
    vorgangstypen = "vorgangstypen"
    parlamente = "parlamente"
    vgidtypen = "vgidtypen"
    dokumententypen = "dokumententypen"


class HashStrategy(StrEnum):
    sha256_bytes = "sha256+bytes"
    sha256_text = "sha256+text"
    sha1_bytes = "sha1+bytes"


class KeytagListing(BaseModel):
    dokumente: list[str] | None = None
    sitzungen: list[str] | None = None
    stationen: list[str] | None = None
    vorgaenge: list[str] | None = None


class Lobbyregistereintrag(BaseModel):
    betroffene_drucksachen: Annotated[
        list[str],
        Field(
            description="Array with associated Drucksachennummern.\nIs not crossreferenced in the database and just added as dataset"
        ),
    ]
    intention: Annotated[
        str,
        Field(description="Subject and reason for influencing the legislative process"),
    ]
    interne_id: Annotated[
        str,
        Field(
            description="Internal ID within the register, necessary to build a url for it"
        ),
    ]
    link: Annotated[AnyUrl, Field(description="direct link to the entry")]
    organisation: Autor


class Mime(StrEnum):
    application_json = "application/json"
    application_pdf = "application/pdf"
    text_plain = "text/plain"
    text_html = "text/html"


class Parlament(StrEnum):
    BT = "BT"
    BR = "BR"
    BV = "BV"
    EK = "EK"
    BB = "BB"
    BY = "BY"
    BE = "BE"
    HB = "HB"
    HH = "HH"
    HE = "HE"
    MV = "MV"
    NI = "NI"
    NW = "NW"
    RP = "RP"
    SL = "SL"
    SN = "SN"
    TH = "TH"
    SH = "SH"
    BW = "BW"
    ST = "ST"


class Value(BaseModel):
    fachgebiet: str | None = None
    lobbyregister: AnyUrl | None = None
    organisation: str
    person: str | None = None


class ReplacementPutRequestInnerAutor(BaseModel):
    replaced_by: Annotated[
        int,
        Field(
            description="This object is replaced by the object with index {} in the 'objects' list above. 0-Based indexing.",
            ge=0,
        ),
    ]
    values: list[Value]


class Value1(BaseModel):
    link: AnyUrl | None = None
    name: Annotated[
        str,
        Field(
            description="Name of the body. 'plenum', 'regierung', 'volk' are reserved"
        ),
    ]
    parlament: Parlament
    wahlperiode: Annotated[int, Field(ge=0)]


class ReplacementPutRequestInnerGremium(BaseModel):
    replaced_by: Annotated[
        int,
        Field(
            description="This object is replaced by the object with index {} in the 'objects' list above. 0-Based indexing.",
            ge=0,
        ),
    ]
    values: list[Value1]


class ReplacementPutRequestInnerString(BaseModel):
    replaced_by: Annotated[
        int,
        Field(
            description="This object is replaced by the object with index {} in the 'objects' list above. 0-Based indexing.",
            ge=0,
        ),
    ]
    values: list[str]


class Object(BaseModel):
    fachgebiet: str | None = None
    lobbyregister: AnyUrl | None = None
    organisation: str
    person: str | None = None


class ReplacementPutRequestAutor(BaseModel):
    objects: list[Object]
    replacing: list[ReplacementPutRequestInnerAutor] | None = None


class Object1(BaseModel):
    link: AnyUrl | None = None
    name: Annotated[
        str,
        Field(
            description="Name of the body. 'plenum', 'regierung', 'volk' are reserved"
        ),
    ]
    parlament: Parlament
    wahlperiode: Annotated[int, Field(ge=0)]


class ReplacementPutRequestGremium(BaseModel):
    objects: list[Object1]
    replacing: list[ReplacementPutRequestInnerGremium] | None = None


class ReplacementPutRequestString(BaseModel):
    objects: list[str]
    replacing: list[ReplacementPutRequestInnerString] | None = None


class Ressort(StrEnum):
    Arbeit = "Arbeit"
    Bildung = "Bildung"
    Digitalisierung = "Digitalisierung"
    Energie = "Energie"
    Ernährung = "Ernährung"
    Europa = "Europa"
    Familie_Senioren = "Familie/Senioren"
    Finanzen = "Finanzen"
    Forschung = "Forschung"
    Forsten = "Forsten"
    Frauen_Gleichstellung = "Frauen/Gleichstellung"
    Gesundheit_Pflege_Prävention = "Gesundheit/Pflege/Prävention"
    Heimat = "Heimat"
    Inneres = "Inneres"
    Integration_Migration = "Integration/Migration"
    Jugend = "Jugend"
    Justiz = "Justiz"
    Kinder = "Kinder"
    Klimaschutz = "Klimaschutz"
    Kommunales = "Kommunales"
    Kunst_Kultur = "Kunst/Kultur"
    Landes__Stadtentwicklung = "Landes-/Stadtentwicklung"
    Ländlicher_Raum = "Ländlicher Raum"
    Landwirtschaft = "Landwirtschaft"
    Soziales = "Soziales"
    Sport = "Sport"
    Tourismus = "Tourismus"
    Umwelt = "Umwelt"
    Verbraucherschutz = "Verbraucherschutz"
    Verkehr_Infrastruktur = "Verkehr/Infrastruktur"
    Wirtschaft = "Wirtschaft"
    Wissenschaft = "Wissenschaft"
    Wohnen_Bau = "Wohnen/Bau"


class Sachgebiet(IntEnum):
    integer_1000 = 1000
    integer_1010 = 1010
    integer_1030 = 1030
    integer_1050 = 1050
    integer_1060 = 1060
    integer_1070 = 1070
    integer_1080 = 1080
    integer_1100 = 1100
    integer_1110 = 1110
    integer_1200 = 1200
    integer_1210 = 1210
    integer_1220 = 1220
    integer_1230 = 1230
    integer_1240 = 1240
    integer_1300 = 1300
    integer_1310 = 1310
    integer_1320 = 1320
    integer_1330 = 1330
    integer_1340 = 1340
    integer_1350 = 1350
    integer_1400 = 1400
    integer_1410 = 1410
    integer_1420 = 1420
    integer_1430 = 1430
    integer_1500 = 1500
    integer_1510 = 1510
    integer_1520 = 1520
    integer_1530 = 1530
    integer_1540 = 1540
    integer_1600 = 1600
    integer_1610 = 1610
    integer_1620 = 1620
    integer_2000 = 2000
    integer_2010 = 2010
    integer_2020 = 2020
    integer_2030 = 2030
    integer_2040 = 2040
    integer_2050 = 2050
    integer_2060 = 2060
    integer_2070 = 2070
    integer_2080 = 2080
    integer_2090 = 2090
    integer_2100 = 2100
    integer_2110 = 2110
    integer_2120 = 2120
    integer_2130 = 2130
    integer_2200 = 2200
    integer_2300 = 2300
    integer_2400 = 2400
    integer_2410 = 2410
    integer_2420 = 2420
    integer_2430 = 2430
    integer_2440 = 2440
    integer_2450 = 2450
    integer_2500 = 2500
    integer_2510 = 2510
    integer_2520 = 2520
    integer_2530 = 2530
    integer_2600 = 2600
    integer_2610 = 2610
    integer_2620 = 2620
    integer_2630 = 2630
    integer_2640 = 2640
    integer_2650 = 2650
    integer_2660 = 2660
    integer_2700 = 2700
    integer_2800 = 2800
    integer_2810 = 2810
    integer_2820 = 2820
    integer_2830 = 2830
    integer_2840 = 2840
    integer_3100 = 3100
    integer_3110 = 3110
    integer_3120 = 3120
    integer_3130 = 3130
    integer_3140 = 3140
    integer_3200 = 3200
    integer_3300 = 3300
    integer_3310 = 3310
    integer_3320 = 3320
    integer_3330 = 3330
    integer_3400 = 3400
    integer_4100 = 4100
    integer_4200 = 4200
    integer_4210 = 4210
    integer_4220 = 4220
    integer_4230 = 4230
    integer_4240 = 4240
    integer_4250 = 4250
    integer_4260 = 4260
    integer_4300 = 4300
    integer_4310 = 4310
    integer_4320 = 4320
    integer_4330 = 4330
    integer_4400 = 4400
    integer_4500 = 4500
    integer_5000 = 5000
    integer_5010 = 5010
    integer_5020 = 5020
    integer_5030 = 5030
    integer_5040 = 5040
    integer_5050 = 5050
    integer_5060 = 5060
    integer_5070 = 5070
    integer_5080 = 5080
    integer_5100 = 5100
    integer_5110 = 5110
    integer_5120 = 5120
    integer_5130 = 5130
    integer_5140 = 5140
    integer_5150 = 5150
    integer_5200 = 5200
    integer_5210 = 5210
    integer_5220 = 5220
    integer_5230 = 5230
    integer_5240 = 5240
    integer_5250 = 5250
    integer_5260 = 5260
    integer_5270 = 5270
    integer_6100 = 6100
    integer_6110 = 6110
    integer_6120 = 6120
    integer_6130 = 6130
    integer_6140 = 6140
    integer_6150 = 6150
    integer_6160 = 6160
    integer_6200 = 6200
    integer_6300 = 6300
    integer_6400 = 6400
    integer_6410 = 6410
    integer_6500 = 6500
    integer_6510 = 6510
    integer_6520 = 6520
    integer_6530 = 6530
    integer_6600 = 6600
    integer_6700 = 6700
    integer_6800 = 6800
    integer_6900 = 6900
    integer_7100 = 7100
    integer_7200 = 7200
    integer_7300 = 7300
    integer_7400 = 7400
    integer_7500 = 7500
    integer_7600 = 7600
    integer_7700 = 7700
    integer_7710 = 7710
    integer_7720 = 7720
    integer_7730 = 7730
    integer_7740 = 7740
    integer_7750 = 7750
    integer_7800 = 7800
    integer_8100 = 8100
    integer_8200 = 8200
    integer_8300 = 8300
    integer_8310 = 8310
    integer_8320 = 8320
    integer_8330 = 8330
    integer_8340 = 8340
    integer_8350 = 8350
    integer_8400 = 8400
    integer_8600 = 8600
    integer_8700 = 8700
    integer_8800 = 8800
    integer_9900 = 9900
    integer_9999 = 9999


class Stationstyp(StrEnum):
    preparl_regent = "preparl-regent"
    preparl_eckpup = "preparl-eckpup"
    preparl_regbsl = "preparl-regbsl"
    preparl_vbegde = "preparl-vbegde"
    preparl_formvs = "preparl-formvs"
    parl_initiativ = "parl-initiativ"
    parl_antragsst = "parl-antragsst"
    parl_ausschber = "parl-ausschber"
    parl_vollvlsgn = "parl-vollvlsgn"
    parl_akzeptanz = "parl-akzeptanz"
    parl_ablehnung = "parl-ablehnung"
    parl_zurueckgz = "parl-zurueckgz"
    parl_ggentwurf = "parl-ggentwurf"
    parl_vermittas = "parl-vermittas"
    parl_verfgstop = "parl-verfgstop"
    postparl_vesja = "postparl-vesja"
    postparl_vesne = "postparl-vesne"
    postparl_gsblt = "postparl-gsblt"
    postparl_kraft = "postparl-kraft"
    sonstig = "sonstig"


class TouchedByInner(BaseModel):
    key: Annotated[
        str | None, Field(description="Key hash of the scraper that touched the object")
    ] = None
    scraper_id: Annotated[
        UUID | None, Field(description="uuid of the scraper that touched this object")
    ] = None


class VgIdent(BaseModel):
    id: str
    typ: str


class Vorgangstyp(StrEnum):
    gg_einspruch = "gg-einspruch"
    gg_zustimmung = "gg-zustimmung"
    gg_land_parl = "gg-land-parl"
    gg_land_volk = "gg-land-volk"
    bw_einsatz = "bw-einsatz"
    sonstig = "sonstig"


class Zusammenfassungstupel(BaseModel):
    inhalt: Annotated[
        str | None,
        Field(
            description="Content of the summary part",
            examples=[
                "Das Gesetz zur Haarfärbeverordnung dient der Umsetzung der EU-Richtline 42/69420 zur Schuppenfreiheit bei Eigenschaftsänderlichen Haarmodifikationen vor..."
            ],
        ),
    ] = None
    typ: Annotated[
        str | None,
        Field(
            description="Type of summary, if the summary is made up of parts\nNOTE: there are some reserved type names:\n- `full`        means summary of the full document without origin info\n- `full-llm`    means summary of the full document, made by llm\n- `full-extern` means summary of the full document, taken from an external source\n\nYou are free to add to these if required, just please stick to the ones available if\npossible",
            examples=["Basisinformationen"],
        ),
    ] = None


class DokumentHash(BaseModel):
    mime: Annotated[
        Mime,
        Field(
            description="The mime of the hashed content.\nIf sha256/1+bytes was used, must be application/pdf;\nIf sha256+text was used, must be text/plain"
        ),
    ]
    strategy: Annotated[
        HashStrategy,
        Field(
            description="The strategy used to compute the hash.\nsha256+text denotes that not the raw file, but the _exact_ volltext field\nof the document was hashed.\nAll text must be utf-8, remain stable under subsequent extraction,\nand mime must be set to text/plain or text/html."
        ),
    ]
    value: Annotated[
        str, Field(description="Hash value as string of hexadecimal octets")
    ]


class Gremium(BaseModel):
    link: AnyUrl | None = None
    name: Annotated[
        str,
        Field(
            description="Name of the body. 'plenum', 'regierung', 'volk' are reserved"
        ),
    ]
    parlament: Parlament
    wahlperiode: Annotated[int, Field(ge=0)]


class HashWrapper(RootModel[str | list[DokumentHash]]):
    root: str | list[DokumentHash]


class ZusammenfassungWrapper(RootModel[str | list[Zusammenfassungstupel]]):
    root: str | list[Zusammenfassungstupel]


class Dokument(BaseModel):
    api_id: Annotated[
        UUID | None,
        Field(
            description="optional, here for future references. Is generated by the server. If you set it use UUID version 5 with your collector id as namespace"
        ),
    ] = None
    autoren: Annotated[
        list[Autor],
        Field(
            description="List of authors of the document. Could be a person, organisation or a parliamentary body"
        ),
    ]
    drucksnr: str | None = None
    hash: Annotated[
        HashWrapper,
        Field(
            description="corresponds to sha256+bytes, here for backwards compatibility"
        ),
    ]
    kurztitel: Annotated[
        str | None,
        Field(description="Brief, Summarized, layman-readable title of the document"),
    ] = None
    link: AnyUrl
    meinung: Annotated[
        int | None,
        Field(
            description="General opinion of the gremium about the Document\nStellungnahme:       1=very bad, 5=very good\nBeschlussempfehlung: 1=rejection recommended, 2-4=accept in changed form, 5=acceptence recommended",
            ge=1,
            le=5,
        ),
    ] = None
    schlagworte: Annotated[
        list[str] | None, Field(description="Keywords associated with this document")
    ] = None
    subdoc_id: Annotated[
        int | None,
        Field(
            description="If a document contains more than one semantically closed document (x opinions in a collected file for example)\nthis denotes the index of the sub-file in question. They can potentially share a hash.",
            ge=0,
        ),
    ] = None
    titel: Annotated[str, Field(description="Official Title of the Document")]
    touched_by: Annotated[
        list[TouchedByInner] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
    typ: Doktyp
    volltext: Annotated[
        str, Field(description="Full text of the document, possibly normalized")
    ]
    vorwort: Annotated[
        str | None, Field(description="Preamble, synopsys or statement of intent")
    ] = None
    zp_erstellt: Annotated[
        AwareDatetime | None,
        Field(
            description="Protocol of the session on 7.3., *created on 8.3.* modified on 9.3."
        ),
    ] = None
    zp_modifiziert: Annotated[
        AwareDatetime,
        Field(
            description="Protocol of the session on 7.3., created on 8.3. *modified on 9.3*."
        ),
    ]
    zp_referenz: Annotated[
        AwareDatetime,
        Field(
            description="Protocol of the *session on 7.3.*, created on 8.3. modified on 9.3."
        ),
    ]
    zusammenfassung: ZusammenfassungWrapper | None = None


class DokumentOrApiId(RootModel[Dokument | UUID]):
    root: Dokument | UUID


class Station(BaseModel):
    additional_links: Annotated[
        list[AnyUrl] | None,
        Field(
            description="Further links to interesting infos for this station",
            examples=["https://example.com/video/of/plenary/session"],
        ),
    ] = None
    api_id: Annotated[
        UUID | None,
        Field(
            description="optional, here for future references. Is generated by the server. If you set it use UUID version 5 with your collector id as namespace"
        ),
    ] = None
    dokumente: Annotated[
        list[DokumentOrApiId],
        Field(
            description="Documents that make up the Station or are associated with it.\nNOTE: At upload time, only complete documents are accepted;\nAt download time, only the API IDs of the documents are passed down to the clients."
        ),
    ]
    gremium: Gremium
    gremium_federf: Annotated[
        bool | None,
        Field(
            description="If the station if of type parl-ausschbsl, this field should be set if the committee is the main committee ('federführend')"
        ),
    ] = None
    link: Annotated[
        AnyUrl | None,
        Field(
            description="Link to a web page describing this station in more detail, NOT to a pdf document"
        ),
    ] = None
    schlagworte: list[str] | None = None
    stellungnahmen: list[DokumentOrApiId] | None = None
    titel: Annotated[
        str | None,
        Field(
            description="optional title, if other data does not provide a proper description"
        ),
    ] = None
    touched_by: Annotated[
        list[TouchedByInner] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
    typ: Stationstyp
    zp_modifiziert: Annotated[
        AwareDatetime | None,
        Field(
            description="Date of the last relevant action within this station. i.e.: last session of a committee"
        ),
    ] = None
    zp_start: Annotated[
        AwareDatetime,
        Field(
            description="Date of the first action within this station. i.e.: First session of a committee"
        ),
    ]


class Top(BaseModel):
    dokumente: Annotated[
        list[DokumentOrApiId] | None,
        Field(description="documents handled in this agenda item"),
    ] = None
    nummer: Annotated[int, Field(description="number of this item on the agenda", ge=0)]
    titel: str
    vorgang_id: Annotated[
        list[UUID] | None,
        Field(
            description="api ids of associated Vorgang objects.\nIs ignored at upload time, but passed at download time.\nThe matching happens via the documents supplied below"
        ),
    ] = None


class Vorgang(BaseModel):
    api_id: Annotated[
        UUID,
        Field(description="Use UUID version 5 with your collector id as namespace"),
    ]
    ids: list[VgIdent] | None = None
    initiatoren: Annotated[
        list[Autor],
        Field(
            description="List of persons or organisations, which initiated the Vorgang."
        ),
    ]
    kurztitel: str | None = None
    links: list[AnyUrl] | None = None
    lobbyregister: Annotated[
        list[Lobbyregistereintrag] | None,
        Field(description="Lobby register annotations from Bundestag sources"),
    ] = None
    ressort: Ressort | None = None
    sachgebiete: Annotated[
        list[Sachgebiet] | None, Field(description="Sachgebiet information")
    ] = None
    stationen: Annotated[
        list[Station],
        Field(
            description="List of stations, the core of what happens in one Proceeding"
        ),
    ]
    titel: str
    touched_by: Annotated[
        list[TouchedByInner] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
    typ: Vorgangstyp
    verfassungsaendernd: Annotated[
        bool,
        Field(
            description="Is this Vorgang directly intended to change the constitution of whatever state it happens\nin?"
        ),
    ]
    wahlperiode: Annotated[
        int, Field(description="number of the electoral period", ge=0)
    ]


class Sitzung(BaseModel):
    api_id: Annotated[
        UUID | None,
        Field(
            description="optional, here for future references. Is generated by the server.\nIf you set it use UUID version 5 with your collector id as namespace"
        ),
    ] = None
    dokumente: Annotated[
        list[DokumentOrApiId] | None,
        Field(description="Announcements, agendas and changed/amended agendas"),
    ] = None
    experten: Annotated[
        list[Autor] | None,
        Field(
            description="List of invited experts. if this is not null or empty, a session is a hearing."
        ),
    ] = None
    gremium: Gremium
    link: AnyUrl | None = None
    nummer: Annotated[int, Field(ge=0)]
    public: bool
    termin: AwareDatetime
    titel: Annotated[str | None, Field(description="Title if applicable")] = None
    tops: list[Top]
    touched_by: Annotated[
        list[TouchedByInner] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
