# generated by datamodel-codegen:
#   filename:  https://staging.api.pazufa.de/openapi.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class ApiKeyStatus(BaseModel):
    expires_at: Annotated[
        AwareDatetime,
        Field(
            description="When this key will expire. If `is_being_rotated` is true, this is the date the rotation is complete."
        ),
    ]
    is_being_rotated: Annotated[
        bool, Field(description="Whether this key is currently in a transition process")
    ]
    scope: Annotated[
        str,
        Field(
            description="Note: inline enums are not fully supported by openapi-generator"
        ),
    ]


class AuthDeleteHeaderParams(BaseModel):
    api_key_delete: str


class Autor(BaseModel):
    fachgebiet: str | None = None
    lobbyregister: AnyUrl | None = None
    organisation: str
    person: str | None = None


class CreateApiKey(BaseModel):
    expires_at: Annotated[
        AwareDatetime | None, Field(description="The expiration date of the API Key")
    ] = None
    scope: Annotated[
        str,
        Field(
            description="Note: inline enums are not fully supported by openapi-generator"
        ),
    ]


class Doktyp(StrEnum):
    eckpunktepapier = "eckpunktepapier"
    preparl_entwurf = "preparl-entwurf"
    entwurf = "entwurf"
    antrag = "antrag"
    anfrage = "anfrage"
    antwort = "antwort"
    mitteilung = "mitteilung"
    beschlussempf = "beschlussempf"
    stellungnahme = "stellungnahme"
    gutachten = "gutachten"
    redeprotokoll = "redeprotokoll"
    tops = "tops"
    tops_aend = "tops-aend"
    tops_ergz = "tops-ergz"
    gesetz = "gesetz"
    sonstig = "sonstig"


class DokumentFormat(StrEnum):
    ftm = "ftm"
    pazufa = "pazufa"


class EnumerationNames(StrEnum):
    schlagworte = "schlagworte"
    stationstypen = "stationstypen"
    vorgangstypen = "vorgangstypen"
    parlamente = "parlamente"
    vgidtypen = "vgidtypen"
    dokumententypen = "dokumententypen"


class KeytagListing(BaseModel):
    dokumente: list[str] | None = None
    sitzungen: list[str] | None = None
    stationen: list[str] | None = None
    vorgaenge: list[str] | None = None


class Lobbyregeintrag(BaseModel):
    betroffene_drucksachen: Annotated[
        list[str],
        Field(
            description="Array with associated Drucksachennummern.\nIs not crossreferenced in the database and just added as dataset"
        ),
    ]
    intention: Annotated[
        str,
        Field(description="Subject and reason for influencing the legislative process"),
    ]
    interne_id: Annotated[
        str,
        Field(
            description="Internal ID within the register, necessary to build a url for it"
        ),
    ]
    link: Annotated[AnyUrl, Field(description="direct link to the entry")]
    organisation: Autor


class Mime(StrEnum):
    application_json = "application/json"
    application_pdf = "application/pdf"
    application_octet_stream = "application/octet-stream"
    text_plain = "text/plain"
    text_html = "text/html"


class Parlament(StrEnum):
    BT = "BT"
    BR = "BR"
    BV = "BV"
    EK = "EK"
    BB = "BB"
    BY = "BY"
    BE = "BE"
    HB = "HB"
    HH = "HH"
    HE = "HE"
    MV = "MV"
    NI = "NI"
    NW = "NW"
    RP = "RP"
    SL = "SL"
    SN = "SN"
    TH = "TH"
    SH = "SH"
    BW = "BW"
    ST = "ST"


class Value(BaseModel):
    fachgebiet: str | None = None
    lobbyregister: AnyUrl | None = None
    organisation: str
    person: str | None = None


class ReplacementPutRequestInnerAutor(BaseModel):
    replaced_by: Annotated[
        int,
        Field(
            description="This object is replaced by the object with index {} in the 'objects' list above. 0-Based indexing.",
            ge=0,
        ),
    ]
    values: list[Value]


class Value1(BaseModel):
    link: AnyUrl | None = None
    name: Annotated[
        str,
        Field(
            description="Name of the body. 'plenum', 'regierung', 'volk' are reserved"
        ),
    ]
    parlament: Parlament
    wahlperiode: Annotated[int, Field(ge=0)]


class ReplacementPutRequestInnerGremium(BaseModel):
    replaced_by: Annotated[
        int,
        Field(
            description="This object is replaced by the object with index {} in the 'objects' list above. 0-Based indexing.",
            ge=0,
        ),
    ]
    values: list[Value1]


class ReplacementPutRequestInnerString(BaseModel):
    replaced_by: Annotated[
        int,
        Field(
            description="This object is replaced by the object with index {} in the 'objects' list above. 0-Based indexing.",
            ge=0,
        ),
    ]
    values: list[str]


class Object(BaseModel):
    fachgebiet: str | None = None
    lobbyregister: AnyUrl | None = None
    organisation: str
    person: str | None = None


class ReplacementPutRequestAutor(BaseModel):
    objects: list[Object]
    replacing: list[ReplacementPutRequestInnerAutor] | None = None


class Object1(BaseModel):
    link: AnyUrl | None = None
    name: Annotated[
        str,
        Field(
            description="Name of the body. 'plenum', 'regierung', 'volk' are reserved"
        ),
    ]
    parlament: Parlament
    wahlperiode: Annotated[int, Field(ge=0)]


class ReplacementPutRequestGremium(BaseModel):
    objects: list[Object1]
    replacing: list[ReplacementPutRequestInnerGremium] | None = None


class ReplacementPutRequestString(BaseModel):
    objects: list[str]
    replacing: list[ReplacementPutRequestInnerString] | None = None


class Stationstyp(StrEnum):
    preparl_regent = "preparl-regent"
    preparl_eckpup = "preparl-eckpup"
    preparl_regbsl = "preparl-regbsl"
    preparl_vbegde = "preparl-vbegde"
    preparl_formvs = "preparl-formvs"
    parl_initiativ = "parl-initiativ"
    parl_antragsst = "parl-antragsst"
    parl_ausschber = "parl-ausschber"
    parl_vollvlsgn = "parl-vollvlsgn"
    parl_akzeptanz = "parl-akzeptanz"
    parl_ablehnung = "parl-ablehnung"
    parl_zurueckgz = "parl-zurueckgz"
    parl_ggentwurf = "parl-ggentwurf"
    parl_vermittas = "parl-vermittas"
    parl_verfgstop = "parl-verfgstop"
    postparl_vesja = "postparl-vesja"
    postparl_vesne = "postparl-vesne"
    postparl_gsblt = "postparl-gsblt"
    postparl_kraft = "postparl-kraft"
    sonstig = "sonstig"


class TouchedByInner(BaseModel):
    key: Annotated[
        str | None, Field(description="Key hash of the scraper that touched the object")
    ] = None
    scraper_id: Annotated[
        UUID | None, Field(description="uuid of the scraper that touched this object")
    ] = None


class VgIdent(BaseModel):
    id: str
    typ: str


class Vorgangstyp(StrEnum):
    gg_einspruch = "gg-einspruch"
    gg_zustimmung = "gg-zustimmung"
    gg_land_parl = "gg-land-parl"
    gg_land_volk = "gg-land-volk"
    bw_einsatz = "bw-einsatz"
    sonstig = "sonstig"


class Dokument(BaseModel):
    api_id: Annotated[
        UUID | None,
        Field(
            description="optional, here for future references. Is generated by the server. If you set it use UUID version 5 with your collector id as namespace"
        ),
    ] = None
    autoren: Annotated[
        list[Autor],
        Field(
            description="List of authors of the document. Could be a person, organisation or a parliamentary body"
        ),
    ]
    drucksnr: str | None = None
    hash: Annotated[
        str,
        Field(
            description="corresponds to sha256+bytes, here for backwards compatibility"
        ),
    ]
    kurztitel: Annotated[
        str | None,
        Field(description="Brief, Summarized, layman-readable title of the document"),
    ] = None
    link: AnyUrl
    meinung: Annotated[
        int | None,
        Field(
            description="General opinion of the gremium about the Document\nStellungnahme:       1=very bad, 5=very good\nBeschlussempfehlung: 1=rejection recommended, 2-4=accept in changed form, 5=acceptence recommended",
            ge=1,
            le=5,
        ),
    ] = None
    schlagworte: Annotated[
        list[str] | None, Field(description="Keywords associated with this document")
    ] = None
    titel: Annotated[str, Field(description="Official Title of the Document")]
    touched_by: Annotated[
        list[TouchedByInner] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
    typ: Doktyp
    volltext: Annotated[
        str, Field(description="Full text of the document, possibly normalized")
    ]
    vorwort: Annotated[
        str | None, Field(description="Preamble, synopsys or statement of intent")
    ] = None
    zp_erstellt: Annotated[
        AwareDatetime | None,
        Field(
            description="Protocol of the session on 7.3., *created on 8.3.* modified on 9.3."
        ),
    ] = None
    zp_modifiziert: Annotated[
        AwareDatetime,
        Field(
            description="Protocol of the session on 7.3., created on 8.3. *modified on 9.3*."
        ),
    ]
    zp_referenz: Annotated[
        AwareDatetime,
        Field(
            description="Protocol of the *session on 7.3.*, created on 8.3. modified on 9.3."
        ),
    ]
    zusammenfassung: Annotated[
        str | None, Field(description="Summary of the document's contents")
    ] = None


class DokumentOrApiId(RootModel[Dokument | UUID]):
    root: Dokument | UUID


class Gremium(BaseModel):
    link: AnyUrl | None = None
    name: Annotated[
        str,
        Field(
            description="Name of the body. 'plenum', 'regierung', 'volk' are reserved"
        ),
    ]
    parlament: Parlament
    wahlperiode: Annotated[int, Field(ge=0)]


class Station(BaseModel):
    additional_links: Annotated[
        list[AnyUrl] | None,
        Field(
            description="Further links to interesting infos for this station",
            examples=["https://example.com/video/of/plenary/session"],
        ),
    ] = None
    api_id: Annotated[
        UUID | None,
        Field(
            description="optional, here for future references. Is generated by the server. If you set it use UUID version 5 with your collector id as namespace"
        ),
    ] = None
    dokumente: Annotated[
        list[DokumentOrApiId],
        Field(
            description="Documents that make up the Station or are associated with it.\nNOTE: At upload time, only complete documents are accepted;\nAt download time, only the API IDs of the documents are passed down to the clients."
        ),
    ]
    gremium: Gremium
    gremium_federf: Annotated[
        bool | None,
        Field(
            description="If the station if of type parl-ausschbsl, this field should be set if the committee is the main committee ('federführend')"
        ),
    ] = None
    link: Annotated[
        AnyUrl | None,
        Field(
            description="Link to a web page describing this station in more detail, NOT to a pdf document"
        ),
    ] = None
    schlagworte: list[str] | None = None
    stellungnahmen: list[DokumentOrApiId] | None = None
    titel: Annotated[
        str | None,
        Field(
            description="optional title, if other data does not provide a proper description"
        ),
    ] = None
    touched_by: Annotated[
        list[TouchedByInner] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
    typ: Stationstyp
    zp_modifiziert: Annotated[
        AwareDatetime | None,
        Field(
            description="Date of the last relevant action within this station. i.e.: last session of a committee"
        ),
    ] = None
    zp_start: Annotated[
        AwareDatetime,
        Field(
            description="Date of the first action within this station. i.e.: First session of a committee"
        ),
    ]


class Top(BaseModel):
    dokumente: Annotated[
        list[DokumentOrApiId] | None,
        Field(description="documents handled in this agenda item"),
    ] = None
    nummer: Annotated[int, Field(description="number of this item on the agenda", ge=0)]
    titel: str
    vorgang_id: Annotated[
        list[UUID] | None,
        Field(
            description="api ids of associated Vorgang objects.\nIs ignored at upload time, but passed at download time.\nThe matching happens via the documents supplied below"
        ),
    ] = None


class Vorgang(BaseModel):
    api_id: Annotated[
        UUID,
        Field(description="Use UUID version 5 with your collector id as namespace"),
    ]
    ids: list[VgIdent] | None = None
    initiatoren: Annotated[
        list[Autor],
        Field(
            description="List of persons or organisations, which initiated the Vorgang."
        ),
    ]
    kurztitel: str | None = None
    links: list[AnyUrl] | None = None
    lobbyregister: list[Lobbyregeintrag] | None = None
    stationen: list[Station]
    titel: str
    touched_by: Annotated[
        list[TouchedByInner] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
    typ: Vorgangstyp
    verfassungsaendernd: Annotated[
        bool,
        Field(
            description="Is this Vorgang directly intended to change the constitution of whatever state it happens\nin?"
        ),
    ]
    wahlperiode: Annotated[
        int, Field(description="number of the electoral period", ge=0)
    ]


class Sitzung(BaseModel):
    api_id: Annotated[
        UUID | None,
        Field(
            description="optional, here for future references. Is generated by the server.\nIf you set it use UUID version 5 with your collector id as namespace"
        ),
    ] = None
    dokumente: Annotated[
        list[DokumentOrApiId] | None,
        Field(description="Announcements, agendas and changed/amended agendas"),
    ] = None
    experten: Annotated[
        list[Autor] | None,
        Field(
            description="List of invited experts. if this is not null or empty, a session is a hearing."
        ),
    ] = None
    gremium: Gremium
    link: AnyUrl | None = None
    nummer: Annotated[int, Field(ge=0)]
    public: bool
    termin: AwareDatetime
    titel: Annotated[str | None, Field(description="Title if applicable")] = None
    tops: list[Top]
    touched_by: Annotated[
        list[TouchedByInner] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
