# GENERATED FILE - DO NOT EDIT.
# Regenerate with `make generate-working-models`; see
# tools/generate_working_models.py.
#
# Lenient mirror of pazufa_corelib.api_model: every field is optional so
# partially collected data can be carried around and type-checked before it is
# complete. Enums are reused from api_model and the models inherit the same
# hardening base, so members compare identical and blanks still become None.
#
# What is deliberately NOT reproduced: required fields, value constraints, and
# the @model_validator hooks. api_model stays the only place that decides
# whether an object is valid - hand it a `model_dump()` to find out.
#
# generated by datamodel-codegen:
#   filename:  api_model.schema.json

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from pydantic import AnyHttpUrl, AnyUrl, Field, RootModel

from pazufa_corelib._api_model_hardening import PaZuFaBaseModel, TzDatetime
from pazufa_corelib.api_model import (
    ApiKeyScope,
    Doktyp,
    HashStrategy,
    Mime,
    Parlament,
    Ressort,
    Sachgebiet,
    Stationstyp,
    Vorgangstyp,
)


class WorkingApiKeyStatus(PaZuFaBaseModel):
    expires_at: Annotated[
        TzDatetime | None,
        Field(
            description="When this key will expire. If `is_being_rotated` is true, this is the date the rotation is complete."
        ),
    ] = None
    is_being_rotated: Annotated[
        bool | None,
        Field(description="Whether this key is currently in a transition process"),
    ] = None
    scope: ApiKeyScope | None = None


class WorkingAuthDeleteHeaderParams(PaZuFaBaseModel):
    api_key_delete: str | None = None


class WorkingAutor(PaZuFaBaseModel):
    fachgebiet: str | None = None
    lobbyregister: AnyHttpUrl | None = None
    organisation: str | None = None
    person: str | None = None


class WorkingCreateApiKey(PaZuFaBaseModel):
    expires_at: Annotated[
        TzDatetime | None, Field(description="The expiration date of the API Key")
    ] = None
    scope: ApiKeyScope | None = None


class WorkingKeytagListing(PaZuFaBaseModel):
    dokumente: list[str] | None = None
    sitzungen: list[str] | None = None
    stationen: list[str] | None = None
    vorgaenge: list[str] | None = None


class WorkingLobbyregistereintrag(PaZuFaBaseModel):
    betroffene_drucksachen: Annotated[
        list[str] | None,
        Field(
            description="Array with associated Drucksachennummern.\nIs not crossreferenced in the database and just added as dataset"
        ),
    ] = None
    intention: Annotated[
        str | None,
        Field(description="Subject and reason for influencing the legislative process"),
    ] = None
    interne_id: Annotated[
        str | None,
        Field(
            description="Internal ID within the register, necessary to build a url for it"
        ),
    ] = None
    link: Annotated[
        AnyHttpUrl | None, Field(description="direct link to the entry")
    ] = None
    organisation: WorkingAutor | None = None


class WorkingReplacingEntryAutor(PaZuFaBaseModel):
    replaced_by: Annotated[
        int | None,
        Field(
            description="This object is replaced by the object with index {} in the 'objects' list above. 0-Based indexing."
        ),
    ] = None
    values: list[WorkingAutor] | None = None


class WorkingReplacingEntryStr(PaZuFaBaseModel):
    replaced_by: Annotated[
        int | None,
        Field(
            description="This object is replaced by the object with index {} in the 'objects' list above. 0-Based indexing."
        ),
    ] = None
    values: list[str] | None = None


class WorkingRotationResponse(PaZuFaBaseModel):
    """Response body of POST /api/v2/auth/rotate.

    The spec declares this response inline rather than under
    `components/schemas`, so the generator does not emit a class for it. Fields
    mirror the inline schema exactly.
    """

    new_api_key: Annotated[
        str | None, Field(description="The newly created API key (shown only once)")
    ] = None
    rotation_complete_date: Annotated[
        TzDatetime | None,
        Field(description="Confirmed date when the old key will be invalidated"),
    ] = None


class WorkingTouchedByEntry(PaZuFaBaseModel):
    key: Annotated[
        str | None, Field(description="Key hash of the scraper that touched the object")
    ] = None
    scraper_id: Annotated[
        UUID | None, Field(description="uuid of the scraper that touched this object")
    ] = None


class WorkingVgIdent(PaZuFaBaseModel):
    id: str | None = None
    typ: str | None = None


class WorkingZusammenfassungstupel(PaZuFaBaseModel):
    inhalt: Annotated[
        str | None,
        Field(
            description="Content of the summary part",
            examples=[
                "Das Gesetz zur Haarfärbeverordnung dient der Umsetzung der EU-Richtline 42/69420 zur Schuppenfreiheit bei Eigenschaftsänderlichen Haarmodifikationen vor..."
            ],
        ),
    ] = None
    typ: Annotated[
        str | None,
        Field(
            description="Type of summary, if the summary is made up of parts\nNOTE: there are some reserved type names:\n- `full`        means summary of the full document without origin info\n- `full-llm`    means summary of the full document, made by llm\n- `full-extern` means summary of the full document, taken from an external source\n\nYou are free to add to these if required, just please stick to the ones available if\npossible",
            examples=["Basisinformationen"],
        ),
    ] = None


class WorkingAutorenPutRequest(PaZuFaBaseModel):
    """Request body for PUT /api/v2/autoren."""

    objects: list[WorkingAutor] | None = None
    replacing: list[WorkingReplacingEntryAutor] | None = None


class WorkingDokumentHash(PaZuFaBaseModel):
    mime: Annotated[
        Mime | None,
        Field(
            description="The mime of the hashed content.\nIf sha256/1+bytes was used, must be application/pdf;\nIf sha256+text was used, must be text/plain"
        ),
    ] = None
    strategy: Annotated[
        HashStrategy | None,
        Field(
            description="The strategy used to compute the hash.\nsha256+text denotes that not the raw file, but the _exact_ volltext field\nof the document was hashed.\nAll text must be utf-8, remain stable under subsequent extraction,\nand mime must be set to text/plain or text/html."
        ),
    ] = None
    value: Annotated[
        str | None, Field(description="Hash value as string of hexadecimal octets")
    ] = None


class WorkingEnumerationPutRequest(PaZuFaBaseModel):
    """Request body for PUT /api/v2/enumeration/{name}."""

    objects: list[str] | None = None
    replacing: list[WorkingReplacingEntryStr] | None = None


class WorkingGremium(PaZuFaBaseModel):
    link: AnyHttpUrl | None = None
    name: Annotated[
        str | None,
        Field(
            description="Name of the body. 'plenum', 'regierung', 'volk' are reserved"
        ),
    ] = None
    parlament: Parlament | None = None
    wahlperiode: int | None = None


class WorkingHashWrapper(RootModel[str | list[WorkingDokumentHash] | None]):
    root: Annotated[
        str | list[WorkingDokumentHash] | None,
        Field(
            description="Either the legacy bare digest or the explicit list of typed hashes.\n\nThe bare string form is the backwards-compatible spelling of\n``sha256+bytes`` (see the ``hash`` field of `Dokument`), so it is validated\nas a sha256 digest rather than as a free string — the generated mirror types\nit as a plain ``str`` and would let a truncated or sha1 digest through."
        ),
    ] = None


class WorkingReplacingEntryGremium(PaZuFaBaseModel):
    replaced_by: Annotated[
        int | None,
        Field(
            description="This object is replaced by the object with index {} in the 'objects' list above. 0-Based indexing."
        ),
    ] = None
    values: list[WorkingGremium] | None = None


class WorkingZusammenfassungWrapper(
    RootModel[str | list[WorkingZusammenfassungstupel] | None]
):
    root: str | list[WorkingZusammenfassungstupel] | None = None


class WorkingDokument(PaZuFaBaseModel):
    api_id: Annotated[
        UUID | None,
        Field(
            description="optional, here for future references. Is generated by the server. If you set it use UUID version 5 with your collector id as namespace"
        ),
    ] = None
    autoren: Annotated[
        list[WorkingAutor] | None,
        Field(
            description="List of authors of the document. Could be a person, organisation or a parliamentary body"
        ),
    ] = None
    drucksnr: str | None = None
    hash: Annotated[
        WorkingHashWrapper | None,
        Field(description="Wrapper that allows for legacy Hashes"),
    ] = None
    kurztitel: Annotated[
        str | None,
        Field(description="Brief, Summarized, layman-readable title of the document"),
    ] = None
    link: AnyHttpUrl | None = None
    meinung: Annotated[
        int | None,
        Field(
            description="General opinion of the gremium about the Document\nStellungnahme:       1=very bad, 5=very good\nBeschlussempfehlung: 1=rejection recommended, 2-4=accept in changed form, 5=acceptence recommended"
        ),
    ] = None
    schlagworte: Annotated[
        list[str] | None, Field(description="Keywords associated with this document")
    ] = None
    subdoc_id: Annotated[
        int | None,
        Field(
            description="If a document contains more than one semantically closed document (x opinions in a collected file for example)\nthis denotes the index of the sub-file in question. They can potentially share a hash."
        ),
    ] = None
    titel: Annotated[
        str | None, Field(description="Official Title of the Document")
    ] = None
    touched_by: Annotated[
        list[WorkingTouchedByEntry] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
    typ: Doktyp | None = None
    volltext: Annotated[
        str | None, Field(description="Full text of the document, possibly normalized")
    ] = None
    vorwort: Annotated[
        str | None, Field(description="Preamble, synopsys or statement of intent")
    ] = None
    zp_erstellt: Annotated[
        TzDatetime | None,
        Field(
            description="Protocol of the session on 7.3., *created on 8.3.* modified on 9.3."
        ),
    ] = None
    zp_modifiziert: Annotated[
        TzDatetime | None,
        Field(
            description="Protocol of the session on 7.3., created on 8.3. *modified on 9.3*."
        ),
    ] = None
    zp_referenz: Annotated[
        TzDatetime | None,
        Field(
            description="Protocol of the *session on 7.3.*, created on 8.3. modified on 9.3."
        ),
    ] = None
    zusammenfassung: WorkingZusammenfassungWrapper | None = None


class WorkingDokumentOrApiId(RootModel[WorkingDokument | UUID | None]):
    root: WorkingDokument | UUID | None = None


class WorkingGremienPutRequest(PaZuFaBaseModel):
    """Request body for PUT /api/v2/gremien."""

    objects: list[WorkingGremium] | None = None
    replacing: list[WorkingReplacingEntryGremium] | None = None


class WorkingStation(PaZuFaBaseModel):
    additional_links: Annotated[
        list[AnyUrl] | None,
        Field(
            description="Further links to interesting infos for this station",
            examples=["https://example.com/video/of/plenary/session"],
        ),
    ] = None
    api_id: Annotated[
        UUID | None,
        Field(
            description="optional, here for future references. Is generated by the server. If you set it use UUID version 5 with your collector id as namespace"
        ),
    ] = None
    dokumente: Annotated[
        list[WorkingDokumentOrApiId] | None,
        Field(
            description="Documents that make up the Station or are associated with it.\nNOTE: At upload time, only complete documents are accepted;\nAt download time, only the API IDs of the documents are passed down to the clients."
        ),
    ] = None
    gremium: WorkingGremium | None = None
    gremium_federf: Annotated[
        bool | None,
        Field(
            description="If the station if of type parl-ausschbsl, this field should be set if the committee is the main committee ('federführend')"
        ),
    ] = None
    link: Annotated[
        AnyHttpUrl | None,
        Field(
            description="Link to a web page describing this station in more detail, NOT to a pdf document"
        ),
    ] = None
    schlagworte: list[str] | None = None
    stellungnahmen: list[WorkingDokumentOrApiId] | None = None
    titel: Annotated[
        str | None,
        Field(
            description="optional title, if other data does not provide a proper description"
        ),
    ] = None
    touched_by: Annotated[
        list[WorkingTouchedByEntry] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
    typ: Stationstyp | None = None
    zp_modifiziert: Annotated[
        TzDatetime | None,
        Field(
            description="Date of the last relevant action within this station. i.e.: last session of a committee"
        ),
    ] = None
    zp_start: Annotated[
        TzDatetime | None,
        Field(
            description="Date of the first action within this station. i.e.: First session of a committee"
        ),
    ] = None


class WorkingTop(PaZuFaBaseModel):
    dokumente: Annotated[
        list[WorkingDokumentOrApiId] | None,
        Field(description="documents handled in this agenda item"),
    ] = None
    nummer: Annotated[
        int | None, Field(description="number of this item on the agenda")
    ] = None
    titel: str | None = None
    vorgang_id: Annotated[
        list[UUID] | None,
        Field(
            description="api ids of associated Vorgang objects.\nIs ignored at upload time, but passed at download time.\nThe matching happens via the documents supplied below"
        ),
    ] = None


class WorkingVorgang(PaZuFaBaseModel):
    api_id: Annotated[
        UUID | None,
        Field(description="Use UUID version 5 with your collector id as namespace"),
    ] = None
    ids: list[WorkingVgIdent] | None = None
    initiatoren: Annotated[
        list[WorkingAutor] | None,
        Field(
            description="List of persons or organisations, which initiated the Vorgang."
        ),
    ] = None
    kurztitel: str | None = None
    links: list[AnyUrl] | None = None
    lobbyregister: list[WorkingLobbyregistereintrag] | None = None
    ressort: Ressort | None = None
    sachgebiete: list[Sachgebiet] | None = None
    stationen: list[WorkingStation] | None = None
    titel: str | None = None
    touched_by: Annotated[
        list[WorkingTouchedByEntry] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
    typ: Vorgangstyp | None = None
    verfassungsaendernd: Annotated[
        bool | None,
        Field(
            description="Is this Vorgang directly intended to change the constitution of whatever state it happens\nin?"
        ),
    ] = None
    wahlperiode: Annotated[
        int | None, Field(description="number of the electoral period")
    ] = None


class WorkingSitzung(PaZuFaBaseModel):
    api_id: Annotated[
        UUID | None,
        Field(
            description="optional, here for future references. Is generated by the server.\nIf you set it use UUID version 5 with your collector id as namespace"
        ),
    ] = None
    dokumente: Annotated[
        list[WorkingDokumentOrApiId] | None,
        Field(description="Announcements, agendas and changed/amended agendas"),
    ] = None
    experten: Annotated[
        list[WorkingAutor] | None,
        Field(
            description="List of invited experts. if this is not null or empty, a session is a hearing."
        ),
    ] = None
    gremium: WorkingGremium | None = None
    link: AnyHttpUrl | None = None
    nummer: int | None = None
    public: bool | None = None
    termin: TzDatetime | None = None
    titel: Annotated[str | None, Field(description="Title if applicable")] = None
    tops: list[WorkingTop] | None = None
    touched_by: Annotated[
        list[WorkingTouchedByEntry] | None,
        Field(
            description="list of scraper uuids / key database ids that have touched this object"
        ),
    ] = None
