# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/Chrystalkey/landtagszusammenfasser/refs/heads/main/docs/specs/openapi.yml

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class KeyTag(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description=(
                "A uniquely identifying string that is generated from key data within the database"
            )
        ),
    ]


class EnumerationNames(StrEnum):
    schlagworte = "schlagworte"
    stationstypen = "stationstypen"
    vorgangstypen = "vorgangstypen"
    parlamente = "parlamente"
    vgidtypen = "vgidtypen"
    dokumententypen = "dokumententypen"


class Scope(StrEnum):
    admin = "admin"
    collector = "collector"
    keyadder = "keyadder"


class CreateApiKey(BaseModel):
    scope: Scope
    expires_at: Annotated[
        AwareDatetime | None,
        Field(
            description="The expiration date of the API Key", examples=["2024-12-31T23:59:59+00:00"]
        ),
    ] = None


class RotationResponse(BaseModel):
    new_api_key: Annotated[str, Field(description="The newly created API key (shown only once)")]
    rotation_complete_date: Annotated[
        AwareDatetime, Field(description="Confirmed date when the old key will be invalidated")
    ]


class ApiKeyStatus(BaseModel):
    scope: Scope
    expires_at: Annotated[
        AwareDatetime,
        Field(
            description=(
                "When this key will expire. If is_being_rotated is true, this is the date the"
                " rotation is complete."
            )
        ),
    ]
    is_being_rotated: Annotated[
        bool, Field(description="Whether this key is currently in a transition process")
    ]


class Parlament(StrEnum):
    BT = "BT"
    BR = "BR"
    BV = "BV"
    EK = "EK"
    BB = "BB"
    BY = "BY"
    BE = "BE"
    HB = "HB"
    HH = "HH"
    HE = "HE"
    MV = "MV"
    NI = "NI"
    NW = "NW"
    RP = "RP"
    SL = "SL"
    SN = "SN"
    TH = "TH"
    SH = "SH"
    BW = "BW"
    ST = "ST"


class Vorgangstyp(StrEnum):
    gg_einspruch = "gg-einspruch"
    gg_zustimmung = "gg-zustimmung"
    gg_land_parl = "gg-land-parl"
    gg_land_volk = "gg-land-volk"
    bw_einsatz = "bw-einsatz"
    sonstig = "sonstig"


class Stationstyp(StrEnum):
    preparl_regent = "preparl-regent"
    preparl_eckpup = "preparl-eckpup"
    preparl_regbsl = "preparl-regbsl"
    preparl_vbegde = "preparl-vbegde"
    parl_initiativ = "parl-initiativ"
    parl_ausschber = "parl-ausschber"
    parl_vollvlsgn = "parl-vollvlsgn"
    parl_akzeptanz = "parl-akzeptanz"
    parl_ablehnung = "parl-ablehnung"
    parl_zurueckgz = "parl-zurueckgz"
    parl_ggentwurf = "parl-ggentwurf"
    postparl_vesja = "postparl-vesja"
    postparl_vesne = "postparl-vesne"
    postparl_gsblt = "postparl-gsblt"
    postparl_kraft = "postparl-kraft"
    sonstig = "sonstig"


class VgIdentTyp(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description=(
                "Typ von Identifikatoren für einen gesamten Vorgang. Offen für was auch immer ein"
                " Parlament benutzt um einen Vorgang zu identifizieren. Aktuell in der Datenbank:"
                " initdrucks, vorgnr, api-id, sonstig bitte keine neue Abkürzung für denselben Typ"
                " erfinden"
            ),
            examples=["initdrucks"],
        ),
    ]


class Doktyp(StrEnum):
    preparl_entwurf = "preparl-entwurf"
    entwurf = "entwurf"
    antrag = "antrag"
    anfrage = "anfrage"
    antwort = "antwort"
    mitteilung = "mitteilung"
    beschlussempf = "beschlussempf"
    stellungnahme = "stellungnahme"
    gutachten = "gutachten"
    redeprotokoll = "redeprotokoll"
    tops = "tops"
    tops_aend = "tops-aend"
    tops_ergz = "tops-ergz"
    sonstig = "sonstig"


class Gremium(BaseModel):
    parlament: Parlament
    wahlperiode: Annotated[int, Field(ge=0)]
    link: AnyUrl | None = None
    name: Annotated[
        str,
        Field(
            description=(
                "Name des betreffenden Gremiums. 'plenum', 'regierung', 'volk' sind reservierte"
                " namen"
            ),
            examples=["Ausschuss für Inneres und Gemüseauflauf"],
        ),
    ]


class TouchedByItem(BaseModel):
    scraper_id: Annotated[
        UUID | None, Field(description="uuid of the scraper that touched this object")
    ] = None
    key: Annotated[
        str | None, Field(description="Key hash of the scraper that touched the object")
    ] = None


class TouchedBy(RootModel[list[TouchedByItem]]):
    root: Annotated[
        list[TouchedByItem],
        Field(description="list of scraper uuids / key database ids that have touched this object"),
    ]


class VgIdent(BaseModel):
    id: Annotated[str, Field(examples=["123e4567-e"])]
    typ: VgIdentTyp


class Autor(BaseModel):
    person: str | None = None
    organisation: str
    fachgebiet: str | None = None
    lobbyregister: AnyUrl | None = None


class Dokument(BaseModel):
    api_id: Annotated[
        UUID | None,
        Field(description="optional, here for future references. Is generated by the server."),
    ] = None
    touched_by: TouchedBy | None = None
    drucksnr: str | None = None
    typ: Doktyp
    titel: Annotated[str, Field(description="Offizieller Titel")]
    kurztitel: Annotated[
        str | None, Field(description="Griffigerer Titel für besseres Verständnis")
    ] = None
    vorwort: Annotated[
        str | None,
        Field(
            description=(
                "Präambel, Vorwort oder Intentionsbeschreibung. Wird für Ähnlichkeitsanalysen von"
                " Gesetzestexten genutzt"
            )
        ),
    ] = None
    volltext: Annotated[str, Field(description="Volltext des Dokuments")]
    zusammenfassung: str | None = None
    zp_modifiziert: Annotated[
        AwareDatetime,
        Field(
            description=(
                "Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am 9.3."
            ),
            examples=["2024-03-09T00:00:00+00:00"],
        ),
    ]
    zp_referenz: Annotated[
        AwareDatetime,
        Field(
            description=(
                "Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am 9.3."
            ),
            examples=["2024-03-07T00:00:00+00:00"],
        ),
    ]
    zp_erstellt: Annotated[
        AwareDatetime | None,
        Field(
            description=(
                "Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am 9.3."
            ),
            examples=["2024-03-08T00:00:00+00:00"],
        ),
    ] = None
    link: AnyUrl
    hash: str
    meinung: Annotated[
        int | None,
        Field(
            description=(
                "Meinungsbild des Dokuments bei Stln / Beschlempf: 1=schlecht, 5=gut bzw."
                " 1=ablehnung empf.,2-4=zust in geänderter Fassung, 5=zustimmung empf."
            ),
            ge=1,
            le=5,
        ),
    ] = None
    schlagworte: list[str] | None = None
    autoren: Annotated[
        list[Autor],
        Field(
            description=(
                "Liste von Autoren des Dokuments. Kann z.B. eine Person, eine Organisation oder ein"
                " Gremium sein."
            )
        ),
    ]


class Station(BaseModel):
    api_id: Annotated[
        UUID | None,
        Field(description="optional, here for future references. Is generated by the server."),
    ] = None
    touched_by: TouchedBy | None = None
    titel: Annotated[
        str | None,
        Field(
            description=(
                "Optionaler Titel, falls die restlichen Daten keinen hinreichenden Rückschluss"
                " zulassen"
            )
        ),
    ] = None
    zp_start: Annotated[
        AwareDatetime,
        Field(
            description=(
                "Datum an dem die erste Aktion dieser Station erstellt wurde, z.B. Erstes"
                " Sitzungsdatum des Ausschusses"
            ),
            examples=["2024-01-01T00:00:00+00:00"],
        ),
    ]
    zp_modifiziert: Annotated[
        AwareDatetime | None,
        Field(
            description=(
                "Letztes relevantes Datum an dem die Station angefasst wurde z.B.: letzte sitzung"
                " oder nächste geplante sitzung"
            ),
            examples=["2024-01-01T00:00:00+00:00"],
        ),
    ] = None
    gremium: Gremium
    gremium_federf: Annotated[
        bool | None,
        Field(
            description=(
                "Ist die Station eine Ausschussberatung gibt dieses Feld an ob es im Federführenden"
                " Ausschuss ist"
            )
        ),
    ] = None
    link: Annotated[
        AnyUrl | None,
        Field(
            description=(
                "Link zu einer Übersichtsseite zu dieser Station. _NICHT_ zu einem Dokument (PDF)"
            )
        ),
    ] = None
    typ: Stationstyp
    trojanergefahr: Annotated[
        int | None,
        Field(
            description="Zahl im Intervall [1;10], die die Gefahr einer Schummelei angeben",
            ge=1,
            le=10,
        ),
    ] = None
    schlagworte: list[str] | None = None
    dokumente: list[Dokument | str]
    additional_links: list[AnyUrl] | None = None
    stellungnahmen: list[Dokument | str] | None = None


class Lobbyregeintrag(BaseModel):
    organisation: Autor
    interne_id: Annotated[
        str, Field(description="Interne ID des Lobbyregisters, notwendig für die bildung von Links")
    ]
    intention: Annotated[
        str,
        Field(
            description=(
                "Lobbyregistereintrag zu dem  Was und Warum man auf den Vorgang Einfluss nehmen"
                " will"
            )
        ),
    ]
    link: Annotated[AnyUrl, Field(description="Direktlink zum Lobbyregistereintrag")]
    betroffene_drucksachen: Annotated[
        list[str],
        Field(
            description=(
                "Stringarray mit betroffenen Drucksachennummern. Wird in der Datenbank _nicht_"
                " integriert und nur flach aufgelegt"
            )
        ),
    ]


class Vorgang(BaseModel):
    api_id: Annotated[UUID, Field(examples=["123e4567-e89b-12d3-a456-426614174000"])]
    touched_by: TouchedBy | None = None
    titel: str
    kurztitel: str | None = None
    wahlperiode: Annotated[
        int, Field(description="Nummer der Wahlperiode, in der der Vorgang stattfindet", ge=0)
    ]
    verfassungsaendernd: bool
    typ: Vorgangstyp
    ids: list[VgIdent] | None = None
    links: list[AnyUrl] | None = None
    initiatoren: Annotated[
        list[Autor],
        Field(
            description=(
                "Liste von Personen oder Organisationen, die den Vorgang initiiert haben. Kann z.B."
                " eine Person, eine Organisation oder ein Gremium sein."
            )
        ),
    ]
    stationen: list[Station]
    lobbyregister: list[Lobbyregeintrag] | None = None


class Top(BaseModel):
    nummer: Annotated[int, Field(description="Nummer des TOPs in einer Sitzung", ge=0)]
    titel: str
    vorgang_id: Annotated[
        list[UUID] | None,
        Field(
            description=(
                "Die Nummer assoziierter Vorgänge. Wird beim Upload ignoriert, aber beim Download"
                " mitgegeben zusammen mit den konkreten Drucksachen"
            )
        ),
    ] = None
    dokumente: Annotated[
        list[Dokument | str] | None,
        Field(description="Die Dokumente, die in diesem TOP besprochen werden sollen"),
    ] = None


class Sitzung(BaseModel):
    api_id: Annotated[
        UUID | None,
        Field(description="optional, here for future references. Is generated by the server."),
    ] = None
    touched_by: TouchedBy | None = None
    titel: Annotated[
        str | None,
        Field(
            description=(
                "Titel wenn anwendbar. In den Ländern sind Themenüberschriften für AS üblich"
            )
        ),
    ] = None
    termin: Annotated[AwareDatetime, Field(examples=["2024-03-15T10:00:00+00:00"])]
    gremium: Gremium
    nummer: Annotated[int, Field(ge=0)]
    public: bool
    link: AnyUrl | None = None
    tops: list[Top]
    dokumente: Annotated[
        list[Dokument | str] | None,
        Field(description="Ankündigungen, TOPs und TOP änderungen bzw. Ergänzungen"),
    ] = None
    experten: Annotated[
        list[Autor] | None,
        Field(
            description=(
                "Optional: Liste von geladenen Experten. (macht aus der Sitzung eine Anhörung)"
            )
        ),
    ] = None
