from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..models.doktyp import Doktyp
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.autor import Autor
    from ..models.dokument_hash import DokumentHash
    from ..models.touched_by_inner import TouchedByInner
    from ..models.zusammenfassungstupel import Zusammenfassungstupel


T = TypeVar("T", bound="Dokument")


@_attrs_define
class Dokument:
    """A document. Could be a protocol, a Drucksache, a statement, ...
    For different objects, only certain properties are optional, which is a known design flaw.
    A Stellungnahme must contain `meinung`, a Gesetzentwurf contains `Vorwort`.
    Since documents can become quite large, they are returned by the server as just their `api_id` in lists

        Attributes:
            autoren (list[Autor]): List of authors of the document. Could be a person, organisation or a parliamentary body
            hash_ (list[DokumentHash] | str):
            link (str):
            titel (str): Official Title of the Document
            typ (Doktyp): Type of a Document
            volltext (str): Full text of the document, possibly normalized
            zp_modifiziert (datetime.datetime): Protocol of the session on 7.3., created on 8.3. *modified on 9.3*.
            zp_referenz (datetime.datetime): Protocol of the *session on 7.3.*, created on 8.3. modified on 9.3.
            api_id (None | Unset | UUID): optional, here for future references. Is generated by the server. If you set it
                use UUID version 5 with your collector id as namespace
            drucksnr (None | str | Unset):
            kurztitel (None | str | Unset): Brief, Summarized, layman-readable title of the document
            meinung (int | None | Unset): General opinion of the gremium about the Document
                Stellungnahme:       1=very bad, 5=very good
                Beschlussempfehlung: 1=rejection recommended, 2-4=accept in changed form, 5=acceptence recommended
            schlagworte (list[str] | Unset): Keywords associated with this document
            subdoc_id (int | None | Unset): If a document contains more than one semantically closed document (x opinions in
                a collected file for example)
                this denotes the index of the sub-file in question. They can potentially share a hash.
            touched_by (list[TouchedByInner] | Unset): list of scraper uuids / key database ids that have touched this
                object
            vorwort (None | str | Unset): Preamble, synopsys or statement of intent
            zp_erstellt (datetime.datetime | None | Unset): Protocol of the session on 7.3., *created on 8.3.* modified on
                9.3.
            zusammenfassung (list[Zusammenfassungstupel] | None | str | Unset):
    """

    autoren: list[Autor]
    hash_: list[DokumentHash] | str
    link: str
    titel: str
    typ: Doktyp
    volltext: str
    zp_modifiziert: datetime.datetime
    zp_referenz: datetime.datetime
    api_id: None | Unset | UUID = UNSET
    drucksnr: None | str | Unset = UNSET
    kurztitel: None | str | Unset = UNSET
    meinung: int | None | Unset = UNSET
    schlagworte: list[str] | Unset = UNSET
    subdoc_id: int | None | Unset = UNSET
    touched_by: list[TouchedByInner] | Unset = UNSET
    vorwort: None | str | Unset = UNSET
    zp_erstellt: datetime.datetime | None | Unset = UNSET
    zusammenfassung: list[Zusammenfassungstupel] | None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        autoren = []
        for autoren_item_data in self.autoren:
            autoren_item = autoren_item_data.to_dict()
            autoren.append(autoren_item)

        hash_: list[dict[str, Any]] | str
        if isinstance(self.hash_, list):
            hash_ = []
            for componentsschemas_hash_wrapper_type_1_item_data in self.hash_:
                componentsschemas_hash_wrapper_type_1_item = componentsschemas_hash_wrapper_type_1_item_data.to_dict()
                hash_.append(componentsschemas_hash_wrapper_type_1_item)

        else:
            hash_ = self.hash_

        link = self.link

        titel = self.titel

        typ = self.typ.value

        volltext = self.volltext

        zp_modifiziert = self.zp_modifiziert.isoformat()

        zp_referenz = self.zp_referenz.isoformat()

        api_id: None | str | Unset
        if isinstance(self.api_id, Unset):
            api_id = UNSET
        elif isinstance(self.api_id, UUID):
            api_id = str(self.api_id)
        else:
            api_id = self.api_id

        drucksnr: None | str | Unset
        if isinstance(self.drucksnr, Unset):
            drucksnr = UNSET
        else:
            drucksnr = self.drucksnr

        kurztitel: None | str | Unset
        if isinstance(self.kurztitel, Unset):
            kurztitel = UNSET
        else:
            kurztitel = self.kurztitel

        meinung: int | None | Unset
        if isinstance(self.meinung, Unset):
            meinung = UNSET
        else:
            meinung = self.meinung

        schlagworte: list[str] | Unset = UNSET
        if not isinstance(self.schlagworte, Unset):
            schlagworte = self.schlagworte

        subdoc_id: int | None | Unset
        if isinstance(self.subdoc_id, Unset):
            subdoc_id = UNSET
        else:
            subdoc_id = self.subdoc_id

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for touched_by_item_data in self.touched_by:
                touched_by_item = touched_by_item_data.to_dict()
                touched_by.append(touched_by_item)

        vorwort: None | str | Unset
        if isinstance(self.vorwort, Unset):
            vorwort = UNSET
        else:
            vorwort = self.vorwort

        zp_erstellt: None | str | Unset
        if isinstance(self.zp_erstellt, Unset):
            zp_erstellt = UNSET
        elif isinstance(self.zp_erstellt, datetime.datetime):
            zp_erstellt = self.zp_erstellt.isoformat()
        else:
            zp_erstellt = self.zp_erstellt

        zusammenfassung: list[dict[str, Any]] | None | str | Unset
        if isinstance(self.zusammenfassung, Unset):
            zusammenfassung = UNSET
        elif isinstance(self.zusammenfassung, list):
            zusammenfassung = []
            for componentsschemas_zusammenfassung_wrapper_type_1_item_data in self.zusammenfassung:
                componentsschemas_zusammenfassung_wrapper_type_1_item = (
                    componentsschemas_zusammenfassung_wrapper_type_1_item_data.to_dict()
                )
                zusammenfassung.append(componentsschemas_zusammenfassung_wrapper_type_1_item)

        else:
            zusammenfassung = self.zusammenfassung

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "autoren": autoren,
                "hash": hash_,
                "link": link,
                "titel": titel,
                "typ": typ,
                "volltext": volltext,
                "zp_modifiziert": zp_modifiziert,
                "zp_referenz": zp_referenz,
            }
        )
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if drucksnr is not UNSET:
            field_dict["drucksnr"] = drucksnr
        if kurztitel is not UNSET:
            field_dict["kurztitel"] = kurztitel
        if meinung is not UNSET:
            field_dict["meinung"] = meinung
        if schlagworte is not UNSET:
            field_dict["schlagworte"] = schlagworte
        if subdoc_id is not UNSET:
            field_dict["subdoc_id"] = subdoc_id
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by
        if vorwort is not UNSET:
            field_dict["vorwort"] = vorwort
        if zp_erstellt is not UNSET:
            field_dict["zp_erstellt"] = zp_erstellt
        if zusammenfassung is not UNSET:
            field_dict["zusammenfassung"] = zusammenfassung

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.autor import Autor
        from ..models.dokument_hash import DokumentHash
        from ..models.touched_by_inner import TouchedByInner
        from ..models.zusammenfassungstupel import Zusammenfassungstupel

        d = dict(src_dict)
        autoren = []
        _autoren = d.pop("autoren")
        for autoren_item_data in _autoren:
            autoren_item = Autor.from_dict(autoren_item_data)

            autoren.append(autoren_item)

        def _parse_hash_(data: object) -> list[DokumentHash] | str:
            try:
                if not isinstance(data, list):
                    raise TypeError()
                componentsschemas_hash_wrapper_type_1 = []
                _componentsschemas_hash_wrapper_type_1 = data
                for componentsschemas_hash_wrapper_type_1_item_data in _componentsschemas_hash_wrapper_type_1:
                    componentsschemas_hash_wrapper_type_1_item = DokumentHash.from_dict(
                        componentsschemas_hash_wrapper_type_1_item_data
                    )

                    componentsschemas_hash_wrapper_type_1.append(componentsschemas_hash_wrapper_type_1_item)

                return componentsschemas_hash_wrapper_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[DokumentHash] | str, data)

        hash_ = _parse_hash_(d.pop("hash"))

        link = d.pop("link")

        titel = d.pop("titel")

        typ = Doktyp(d.pop("typ"))

        volltext = d.pop("volltext")

        zp_modifiziert = isoparse(d.pop("zp_modifiziert"))

        zp_referenz = isoparse(d.pop("zp_referenz"))

        def _parse_api_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                api_id_type_0 = UUID(data)

                return api_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        api_id = _parse_api_id(d.pop("api_id", UNSET))

        def _parse_drucksnr(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        drucksnr = _parse_drucksnr(d.pop("drucksnr", UNSET))

        def _parse_kurztitel(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        kurztitel = _parse_kurztitel(d.pop("kurztitel", UNSET))

        def _parse_meinung(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        meinung = _parse_meinung(d.pop("meinung", UNSET))

        schlagworte = cast(list[str], d.pop("schlagworte", UNSET))

        def _parse_subdoc_id(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        subdoc_id = _parse_subdoc_id(d.pop("subdoc_id", UNSET))

        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByInner] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for touched_by_item_data in _touched_by:
                touched_by_item = TouchedByInner.from_dict(touched_by_item_data)

                touched_by.append(touched_by_item)

        def _parse_vorwort(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        vorwort = _parse_vorwort(d.pop("vorwort", UNSET))

        def _parse_zp_erstellt(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                zp_erstellt_type_0 = isoparse(data)

                return zp_erstellt_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        zp_erstellt = _parse_zp_erstellt(d.pop("zp_erstellt", UNSET))

        def _parse_zusammenfassung(data: object) -> list[Zusammenfassungstupel] | None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                componentsschemas_zusammenfassung_wrapper_type_1 = []
                _componentsschemas_zusammenfassung_wrapper_type_1 = data
                for (
                    componentsschemas_zusammenfassung_wrapper_type_1_item_data
                ) in _componentsschemas_zusammenfassung_wrapper_type_1:
                    componentsschemas_zusammenfassung_wrapper_type_1_item = Zusammenfassungstupel.from_dict(
                        componentsschemas_zusammenfassung_wrapper_type_1_item_data
                    )

                    componentsschemas_zusammenfassung_wrapper_type_1.append(
                        componentsschemas_zusammenfassung_wrapper_type_1_item
                    )

                return componentsschemas_zusammenfassung_wrapper_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[Zusammenfassungstupel] | None | str | Unset, data)

        zusammenfassung = _parse_zusammenfassung(d.pop("zusammenfassung", UNSET))

        dokument = cls(
            autoren=autoren,
            hash_=hash_,
            link=link,
            titel=titel,
            typ=typ,
            volltext=volltext,
            zp_modifiziert=zp_modifiziert,
            zp_referenz=zp_referenz,
            api_id=api_id,
            drucksnr=drucksnr,
            kurztitel=kurztitel,
            meinung=meinung,
            schlagworte=schlagworte,
            subdoc_id=subdoc_id,
            touched_by=touched_by,
            vorwort=vorwort,
            zp_erstellt=zp_erstellt,
            zusammenfassung=zusammenfassung,
        )

        dokument.additional_properties = d
        return dokument

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
