from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.autor import Autor
    from ..models.dokument import Dokument
    from ..models.gremium import Gremium
    from ..models.top import Top
    from ..models.touched_by_inner import TouchedByInner


T = TypeVar("T", bound="Sitzung")


@_attrs_define
class Sitzung:
    """plenary session, committee session or committee hearing.
    A session is a hearing if experts are invited.

        Attributes:
            gremium (Gremium): A body in which decisions can be made: committees, plenary halls, cabinett, peoples, ...
            nummer (int):
            public (bool):
            termin (datetime.datetime):
            tops (list[Top]):
            api_id (None | Unset | UUID): optional, here for future references. Is generated by the server.
                If you set it use UUID version 5 with your collector id as namespace
            dokumente (list[Dokument | UUID] | Unset): Announcements, agendas and changed/amended agendas
            experten (list[Autor] | Unset): List of invited experts. if this is not null or empty, a session is a hearing.
            link (None | str | Unset):
            titel (None | str | Unset): Title if applicable
            touched_by (list[TouchedByInner] | Unset): list of scraper uuids / key database ids that have touched this
                object
    """

    gremium: Gremium
    nummer: int
    public: bool
    termin: datetime.datetime
    tops: list[Top]
    api_id: None | Unset | UUID = UNSET
    dokumente: list[Dokument | UUID] | Unset = UNSET
    experten: list[Autor] | Unset = UNSET
    link: None | str | Unset = UNSET
    titel: None | str | Unset = UNSET
    touched_by: list[TouchedByInner] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.dokument import Dokument

        gremium = self.gremium.to_dict()

        nummer = self.nummer

        public = self.public

        termin = self.termin.isoformat()

        tops = []
        for tops_item_data in self.tops:
            tops_item = tops_item_data.to_dict()
            tops.append(tops_item)

        api_id: None | str | Unset
        if isinstance(self.api_id, Unset):
            api_id = UNSET
        elif isinstance(self.api_id, UUID):
            api_id = str(self.api_id)
        else:
            api_id = self.api_id

        dokumente: list[dict[str, Any] | str] | Unset = UNSET
        if not isinstance(self.dokumente, Unset):
            dokumente = []
            for dokumente_item_data in self.dokumente:
                dokumente_item: dict[str, Any] | str
                if isinstance(dokumente_item_data, Dokument):
                    dokumente_item = dokumente_item_data.to_dict()
                else:
                    dokumente_item = str(dokumente_item_data)

                dokumente.append(dokumente_item)

        experten: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.experten, Unset):
            experten = []
            for experten_item_data in self.experten:
                experten_item = experten_item_data.to_dict()
                experten.append(experten_item)

        link: None | str | Unset
        if isinstance(self.link, Unset):
            link = UNSET
        else:
            link = self.link

        titel: None | str | Unset
        if isinstance(self.titel, Unset):
            titel = UNSET
        else:
            titel = self.titel

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for touched_by_item_data in self.touched_by:
                touched_by_item = touched_by_item_data.to_dict()
                touched_by.append(touched_by_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "gremium": gremium,
                "nummer": nummer,
                "public": public,
                "termin": termin,
                "tops": tops,
            }
        )
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if dokumente is not UNSET:
            field_dict["dokumente"] = dokumente
        if experten is not UNSET:
            field_dict["experten"] = experten
        if link is not UNSET:
            field_dict["link"] = link
        if titel is not UNSET:
            field_dict["titel"] = titel
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.autor import Autor
        from ..models.dokument import Dokument
        from ..models.gremium import Gremium
        from ..models.top import Top
        from ..models.touched_by_inner import TouchedByInner

        d = dict(src_dict)
        gremium = Gremium.from_dict(d.pop("gremium"))

        nummer = d.pop("nummer")

        public = d.pop("public")

        termin = isoparse(d.pop("termin"))

        tops = []
        _tops = d.pop("tops")
        for tops_item_data in _tops:
            tops_item = Top.from_dict(tops_item_data)

            tops.append(tops_item)

        def _parse_api_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                api_id_type_0 = UUID(data)

                return api_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        api_id = _parse_api_id(d.pop("api_id", UNSET))

        _dokumente = d.pop("dokumente", UNSET)
        dokumente: list[Dokument | UUID] | Unset = UNSET
        if _dokumente is not UNSET:
            dokumente = []
            for dokumente_item_data in _dokumente:

                def _parse_dokumente_item(data: object) -> Dokument | UUID:
                    try:
                        if not isinstance(data, dict):
                            raise TypeError()
                        componentsschemas_dokument_or_api_id_type_0 = Dokument.from_dict(data)

                        return componentsschemas_dokument_or_api_id_type_0
                    except (TypeError, ValueError, AttributeError, KeyError):
                        pass
                    if not isinstance(data, str):
                        raise TypeError()
                    componentsschemas_dokument_or_api_id_type_1 = UUID(data)

                    return componentsschemas_dokument_or_api_id_type_1

                dokumente_item = _parse_dokumente_item(dokumente_item_data)

                dokumente.append(dokumente_item)

        _experten = d.pop("experten", UNSET)
        experten: list[Autor] | Unset = UNSET
        if _experten is not UNSET:
            experten = []
            for experten_item_data in _experten:
                experten_item = Autor.from_dict(experten_item_data)

                experten.append(experten_item)

        def _parse_link(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        link = _parse_link(d.pop("link", UNSET))

        def _parse_titel(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        titel = _parse_titel(d.pop("titel", UNSET))

        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByInner] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for touched_by_item_data in _touched_by:
                touched_by_item = TouchedByInner.from_dict(touched_by_item_data)

                touched_by.append(touched_by_item)

        sitzung = cls(
            gremium=gremium,
            nummer=nummer,
            public=public,
            termin=termin,
            tops=tops,
            api_id=api_id,
            dokumente=dokumente,
            experten=experten,
            link=link,
            titel=titel,
            touched_by=touched_by,
        )

        sitzung.additional_properties = d
        return sitzung

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
