from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..models.stationstyp import Stationstyp
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.dokument import Dokument
    from ..models.gremium import Gremium
    from ..models.touched_by_inner import TouchedByInner


T = TypeVar("T", bound="Station")


@_attrs_define
class Station:
    """In many ways a station is the heart of this API.
    Every Vorgang consists of stations, which have only very few required fields.
    They represent meaningful steps that any Vorgang takes from start to finish.
    For further details, see the documentation.

        Attributes:
            dokumente (list[Dokument | UUID]): Documents that make up the Station or are associated with it.
                NOTE: At upload time, only complete documents are accepted;
                At download time, only the API IDs of the documents are passed down to the clients.
            gremium (Gremium): A body in which decisions can be made: committees, plenary halls, cabinett, peoples, ...
            typ (Stationstyp): Substantive legislative steps, that a Vorgang can pass on its way to a law or rejection or
                similar endings.
                The categorisation pre/postparl is to a degree arbitrary, these are just identifiers.
            zp_start (datetime.datetime): Date of the first action within this station. i.e.: First session of a committee
            additional_links (list[str] | Unset): Further links to interesting infos for this station Example:
                https://example.com/video/of/plenary/session.
            api_id (None | Unset | UUID): optional, here for future references. Is generated by the server. If you set it
                use UUID version 5 with your collector id as namespace
            gremium_federf (bool | None | Unset): If the station if of type parl-ausschbsl, this field should be set if the
                committee is the main committee ('federführend')
            link (None | str | Unset): Link to a web page describing this station in more detail, NOT to a pdf document
            schlagworte (list[str] | Unset):
            stellungnahmen (list[Dokument | UUID] | Unset):
            titel (None | str | Unset): optional title, if other data does not provide a proper description
            touched_by (list[TouchedByInner] | Unset): list of scraper uuids / key database ids that have touched this
                object
            zp_modifiziert (datetime.datetime | None | Unset): Date of the last relevant action within this station. i.e.:
                last session of a committee
    """

    dokumente: list[Dokument | UUID]
    gremium: Gremium
    typ: Stationstyp
    zp_start: datetime.datetime
    additional_links: list[str] | Unset = UNSET
    api_id: None | Unset | UUID = UNSET
    gremium_federf: bool | None | Unset = UNSET
    link: None | str | Unset = UNSET
    schlagworte: list[str] | Unset = UNSET
    stellungnahmen: list[Dokument | UUID] | Unset = UNSET
    titel: None | str | Unset = UNSET
    touched_by: list[TouchedByInner] | Unset = UNSET
    zp_modifiziert: datetime.datetime | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.dokument import Dokument

        dokumente = []
        for dokumente_item_data in self.dokumente:
            dokumente_item: dict[str, Any] | str
            if isinstance(dokumente_item_data, Dokument):
                dokumente_item = dokumente_item_data.to_dict()
            else:
                dokumente_item = str(dokumente_item_data)

            dokumente.append(dokumente_item)

        gremium = self.gremium.to_dict()

        typ = self.typ.value

        zp_start = self.zp_start.isoformat()

        additional_links: list[str] | Unset = UNSET
        if not isinstance(self.additional_links, Unset):
            additional_links = self.additional_links

        api_id: None | str | Unset
        if isinstance(self.api_id, Unset):
            api_id = UNSET
        elif isinstance(self.api_id, UUID):
            api_id = str(self.api_id)
        else:
            api_id = self.api_id

        gremium_federf: bool | None | Unset
        if isinstance(self.gremium_federf, Unset):
            gremium_federf = UNSET
        else:
            gremium_federf = self.gremium_federf

        link: None | str | Unset
        if isinstance(self.link, Unset):
            link = UNSET
        else:
            link = self.link

        schlagworte: list[str] | Unset = UNSET
        if not isinstance(self.schlagworte, Unset):
            schlagworte = self.schlagworte

        stellungnahmen: list[dict[str, Any] | str] | Unset = UNSET
        if not isinstance(self.stellungnahmen, Unset):
            stellungnahmen = []
            for stellungnahmen_item_data in self.stellungnahmen:
                stellungnahmen_item: dict[str, Any] | str
                if isinstance(stellungnahmen_item_data, Dokument):
                    stellungnahmen_item = stellungnahmen_item_data.to_dict()
                else:
                    stellungnahmen_item = str(stellungnahmen_item_data)

                stellungnahmen.append(stellungnahmen_item)

        titel: None | str | Unset
        if isinstance(self.titel, Unset):
            titel = UNSET
        else:
            titel = self.titel

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for touched_by_item_data in self.touched_by:
                touched_by_item = touched_by_item_data.to_dict()
                touched_by.append(touched_by_item)

        zp_modifiziert: None | str | Unset
        if isinstance(self.zp_modifiziert, Unset):
            zp_modifiziert = UNSET
        elif isinstance(self.zp_modifiziert, datetime.datetime):
            zp_modifiziert = self.zp_modifiziert.isoformat()
        else:
            zp_modifiziert = self.zp_modifiziert

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "dokumente": dokumente,
                "gremium": gremium,
                "typ": typ,
                "zp_start": zp_start,
            }
        )
        if additional_links is not UNSET:
            field_dict["additional_links"] = additional_links
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if gremium_federf is not UNSET:
            field_dict["gremium_federf"] = gremium_federf
        if link is not UNSET:
            field_dict["link"] = link
        if schlagworte is not UNSET:
            field_dict["schlagworte"] = schlagworte
        if stellungnahmen is not UNSET:
            field_dict["stellungnahmen"] = stellungnahmen
        if titel is not UNSET:
            field_dict["titel"] = titel
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by
        if zp_modifiziert is not UNSET:
            field_dict["zp_modifiziert"] = zp_modifiziert

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.dokument import Dokument
        from ..models.gremium import Gremium
        from ..models.touched_by_inner import TouchedByInner

        d = dict(src_dict)
        dokumente = []
        _dokumente = d.pop("dokumente")
        for dokumente_item_data in _dokumente:

            def _parse_dokumente_item(data: object) -> Dokument | UUID:
                try:
                    if not isinstance(data, dict):
                        raise TypeError()
                    componentsschemas_dokument_or_api_id_type_0 = Dokument.from_dict(data)

                    return componentsschemas_dokument_or_api_id_type_0
                except (TypeError, ValueError, AttributeError, KeyError):
                    pass
                if not isinstance(data, str):
                    raise TypeError()
                componentsschemas_dokument_or_api_id_type_1 = UUID(data)

                return componentsschemas_dokument_or_api_id_type_1

            dokumente_item = _parse_dokumente_item(dokumente_item_data)

            dokumente.append(dokumente_item)

        gremium = Gremium.from_dict(d.pop("gremium"))

        typ = Stationstyp(d.pop("typ"))

        zp_start = isoparse(d.pop("zp_start"))

        additional_links = cast(list[str], d.pop("additional_links", UNSET))

        def _parse_api_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                api_id_type_0 = UUID(data)

                return api_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        api_id = _parse_api_id(d.pop("api_id", UNSET))

        def _parse_gremium_federf(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        gremium_federf = _parse_gremium_federf(d.pop("gremium_federf", UNSET))

        def _parse_link(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        link = _parse_link(d.pop("link", UNSET))

        schlagworte = cast(list[str], d.pop("schlagworte", UNSET))

        _stellungnahmen = d.pop("stellungnahmen", UNSET)
        stellungnahmen: list[Dokument | UUID] | Unset = UNSET
        if _stellungnahmen is not UNSET:
            stellungnahmen = []
            for stellungnahmen_item_data in _stellungnahmen:

                def _parse_stellungnahmen_item(data: object) -> Dokument | UUID:
                    try:
                        if not isinstance(data, dict):
                            raise TypeError()
                        componentsschemas_dokument_or_api_id_type_0 = Dokument.from_dict(data)

                        return componentsschemas_dokument_or_api_id_type_0
                    except (TypeError, ValueError, AttributeError, KeyError):
                        pass
                    if not isinstance(data, str):
                        raise TypeError()
                    componentsschemas_dokument_or_api_id_type_1 = UUID(data)

                    return componentsschemas_dokument_or_api_id_type_1

                stellungnahmen_item = _parse_stellungnahmen_item(stellungnahmen_item_data)

                stellungnahmen.append(stellungnahmen_item)

        def _parse_titel(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        titel = _parse_titel(d.pop("titel", UNSET))

        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByInner] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for touched_by_item_data in _touched_by:
                touched_by_item = TouchedByInner.from_dict(touched_by_item_data)

                touched_by.append(touched_by_item)

        def _parse_zp_modifiziert(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                zp_modifiziert_type_0 = isoparse(data)

                return zp_modifiziert_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        zp_modifiziert = _parse_zp_modifiziert(d.pop("zp_modifiziert", UNSET))

        station = cls(
            dokumente=dokumente,
            gremium=gremium,
            typ=typ,
            zp_start=zp_start,
            additional_links=additional_links,
            api_id=api_id,
            gremium_federf=gremium_federf,
            link=link,
            schlagworte=schlagworte,
            stellungnahmen=stellungnahmen,
            titel=titel,
            touched_by=touched_by,
            zp_modifiziert=zp_modifiziert,
        )

        station.additional_properties = d
        return station

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
