from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..models.doktyp import Doktyp
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.autor import Autor
    from ..models.touched_by_item import TouchedByItem


T = TypeVar("T", bound="Dokument")


@_attrs_define
class Dokument:
    r"""Ein Dokument. Kann z.B. ein Protokoll, eine Drucksache oder eine Stellungnahme sein. Man beachte, dass für
    verschiedene Typen verschiedene Felder nur formal optional sind. So ist zum Beispiel für jede Stellungnahme eine
    Meinung gefragt und für jeden Gesetzesentwurf ein Vorwort. Da Dokumente relativ große Objekte werden können (O(kB)),
    wird überall wo sie Teilobjekte sind (bei Stationen und Sitzungen) nur die UUID vom Server returned, und das
    Dokument muss in einem zweiten Request geladen werden.

        Example:
            {'api_id': 'a1b2c3d4-e5f6-7890-abcd-1234567890ab', 'autoren': [{'fachgebiet': 'Wahlrecht', 'organisation':
                'Bundesministerium des Innern', 'person': 'Dr. Maria Schmidt'}], 'drucksnr': 'BT-Drs. 20/12345', 'hash':
                'a1b2c3d4e5f6g7h8i9j0', 'kurztitel': 'Änderung des Bundeswahlgesetzes', 'link':
                'https://dip.bundestag.de/dokument/12345', 'meinung': 4, 'schlagworte': ['wahlrecht', 'bundestagswahl',
                'reform'], 'titel': 'Entwurf eines Gesetzes zur Änderung des Bundeswahlgesetzes', 'typ': 'entwurf', 'volltext':
                'Der Bundestag hat mit Zustimmung des Bundesrates das folgende Gesetz beschlossen:\n\nArtikel 1\nÄnderung des
                Bundeswahlgesetzes\n\nDas Bundeswahlgesetz in der Fassung der Bekanntmachung vom 23. Juli 1993 (BGBl. I S. 1288,
                1594) wird wie folgt geändert:\n\n1. § 1 Absatz 1 wird wie folgt gefasst: [...]', 'vorwort': 'Mit dem
                vorliegenden Entwurf soll das Bundeswahlgesetz an die aktuellen Anforderungen angepasst werden.', 'zp_erstellt':
                '2024-03-10T09:15:00+01:00', 'zp_modifiziert': '2024-03-15T14:30:00+01:00', 'zp_referenz':
                '2024-03-01T00:00:00+01:00', 'zusammenfassung': 'Änderung des Bundeswahlgesetzes zur Anpassung an aktuelle
                Anforderungen.'}

        Attributes:
            autoren (list[Autor]): Liste von Autoren des Dokuments. Kann z.B. eine Person, eine Organisation oder ein
                Gremium sein.
            hash_ (str):
            link (str):
            titel (str): Offizieller Titel
            typ (Doktyp): Typ eines Dokuments. Beschreibt explizit nicht den Kontext, sondern nur den Typ des Inhalts. (z.B.
                'tops' kann sowohl für Plenarsitzungen als auch für Ausschusssitzungen relevant sein)
            volltext (str): Volltext des Dokuments
            zp_modifiziert (datetime.datetime): Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am
                9.3. Example: 2024-03-09T00:00:00+00:00.
            zp_referenz (datetime.datetime): Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert am 9.3.
                Example: 2024-03-07T00:00:00+00:00.
            api_id (UUID | Unset): optional, here for future references. Is generated by the server.
            drucksnr (str | Unset):
            kurztitel (str | Unset): Griffigerer Titel für besseres Verständnis
            meinung (int | Unset): Meinungsbild des Dokuments bei Stln / Beschlempf: 1=schlecht, 5=gut bzw. 1=ablehnung
                empf.,2-4=zust in geänderter Fassung, 5=zustimmung empf.
            schlagworte (list[str] | Unset):
            touched_by (list[TouchedByItem] | Unset): list of scraper uuids / key database ids that have touched this object
            vorwort (str | Unset): Präambel, Vorwort oder Intentionsbeschreibung. Wird für Ähnlichkeitsanalysen von
                Gesetzestexten genutzt
            zp_erstellt (datetime.datetime | Unset): Plenarprotokoll für die Sitzung am 7.3., erstellt am 8.3. modifiziert
                am 9.3. Example: 2024-03-08T00:00:00+00:00.
            zusammenfassung (str | Unset):
    """

    autoren: list[Autor]
    hash_: str
    link: str
    titel: str
    typ: Doktyp
    volltext: str
    zp_modifiziert: datetime.datetime
    zp_referenz: datetime.datetime
    api_id: UUID | Unset = UNSET
    drucksnr: str | Unset = UNSET
    kurztitel: str | Unset = UNSET
    meinung: int | Unset = UNSET
    schlagworte: list[str] | Unset = UNSET
    touched_by: list[TouchedByItem] | Unset = UNSET
    vorwort: str | Unset = UNSET
    zp_erstellt: datetime.datetime | Unset = UNSET
    zusammenfassung: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        autoren = []
        for autoren_item_data in self.autoren:
            autoren_item = autoren_item_data.to_dict()
            autoren.append(autoren_item)

        hash_ = self.hash_

        link = self.link

        titel = self.titel

        typ = self.typ.value

        volltext = self.volltext

        zp_modifiziert = self.zp_modifiziert.isoformat()

        zp_referenz = self.zp_referenz.isoformat()

        api_id: str | Unset = UNSET
        if not isinstance(self.api_id, Unset):
            api_id = str(self.api_id)

        drucksnr = self.drucksnr

        kurztitel = self.kurztitel

        meinung = self.meinung

        schlagworte: list[str] | Unset = UNSET
        if not isinstance(self.schlagworte, Unset):
            schlagworte = self.schlagworte

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for componentsschemastouched_by_item_data in self.touched_by:
                componentsschemastouched_by_item = componentsschemastouched_by_item_data.to_dict()
                touched_by.append(componentsschemastouched_by_item)

        vorwort = self.vorwort

        zp_erstellt: str | Unset = UNSET
        if not isinstance(self.zp_erstellt, Unset):
            zp_erstellt = self.zp_erstellt.isoformat()

        zusammenfassung = self.zusammenfassung

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "autoren": autoren,
                "hash": hash_,
                "link": link,
                "titel": titel,
                "typ": typ,
                "volltext": volltext,
                "zp_modifiziert": zp_modifiziert,
                "zp_referenz": zp_referenz,
            }
        )
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if drucksnr is not UNSET:
            field_dict["drucksnr"] = drucksnr
        if kurztitel is not UNSET:
            field_dict["kurztitel"] = kurztitel
        if meinung is not UNSET:
            field_dict["meinung"] = meinung
        if schlagworte is not UNSET:
            field_dict["schlagworte"] = schlagworte
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by
        if vorwort is not UNSET:
            field_dict["vorwort"] = vorwort
        if zp_erstellt is not UNSET:
            field_dict["zp_erstellt"] = zp_erstellt
        if zusammenfassung is not UNSET:
            field_dict["zusammenfassung"] = zusammenfassung

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.autor import Autor
        from ..models.touched_by_item import TouchedByItem

        d = dict(src_dict)
        autoren = []
        _autoren = d.pop("autoren")
        for autoren_item_data in _autoren:
            autoren_item = Autor.from_dict(autoren_item_data)

            autoren.append(autoren_item)

        hash_ = d.pop("hash")

        link = d.pop("link")

        titel = d.pop("titel")

        typ = Doktyp(d.pop("typ"))

        volltext = d.pop("volltext")

        zp_modifiziert = isoparse(d.pop("zp_modifiziert"))

        zp_referenz = isoparse(d.pop("zp_referenz"))

        _api_id = d.pop("api_id", UNSET)
        api_id: UUID | Unset
        if isinstance(_api_id, Unset):
            api_id = UNSET
        else:
            api_id = UUID(_api_id)

        drucksnr = d.pop("drucksnr", UNSET)

        kurztitel = d.pop("kurztitel", UNSET)

        meinung = d.pop("meinung", UNSET)

        schlagworte = cast(list[str], d.pop("schlagworte", UNSET))

        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByItem] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for componentsschemastouched_by_item_data in _touched_by:
                componentsschemastouched_by_item = TouchedByItem.from_dict(componentsschemastouched_by_item_data)

                touched_by.append(componentsschemastouched_by_item)

        vorwort = d.pop("vorwort", UNSET)

        _zp_erstellt = d.pop("zp_erstellt", UNSET)
        zp_erstellt: datetime.datetime | Unset
        if isinstance(_zp_erstellt, Unset):
            zp_erstellt = UNSET
        else:
            zp_erstellt = isoparse(_zp_erstellt)

        zusammenfassung = d.pop("zusammenfassung", UNSET)

        dokument = cls(
            autoren=autoren,
            hash_=hash_,
            link=link,
            titel=titel,
            typ=typ,
            volltext=volltext,
            zp_modifiziert=zp_modifiziert,
            zp_referenz=zp_referenz,
            api_id=api_id,
            drucksnr=drucksnr,
            kurztitel=kurztitel,
            meinung=meinung,
            schlagworte=schlagworte,
            touched_by=touched_by,
            vorwort=vorwort,
            zp_erstellt=zp_erstellt,
            zusammenfassung=zusammenfassung,
        )

        dokument.additional_properties = d
        return dokument

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
