from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.autor import Autor
    from ..models.dokument import Dokument
    from ..models.gremium import Gremium
    from ..models.top import Top
    from ..models.touched_by_item import TouchedByItem


T = TypeVar("T", bound="Sitzung")


@_attrs_define
class Sitzung:
    r"""Sitzung oder Anhörung. Eine Anhörung wird es, wenn Experten geladen werden. Abstrahiert und kann daher sowohl
    Plenarsitzung als auch Ausschusssitzung sein.

        Example:
            {'api_id': 'b1a2c3d4-e5f6-7890-fedc-1234567890ab', 'dokumente': [{'api_id':
                'c1d2e3f4-a5b6-7890-cdef-1234567890gh', 'autoren': [{'organisation': 'Deutscher Bundestag'}], 'hash':
                'a1b2c3d4e5f6g7h8i9j0', 'link': 'https://www.bundestag.de/tagesordnung/20240520', 'titel': 'Tagesordnung der
                143. Sitzung des Deutschen Bundestages', 'typ': 'tops', 'volltext': 'TOP 1: Eröffnung der Sitzung\nTOP 2:
                Fragestunde\nTOP 3: Erste Beratung des Gesetzentwurfs zur Änderung des Bundeswahlgesetzes\n...',
                'zp_modifiziert': '2024-05-15T14:30:00+02:00', 'zp_referenz': '2024-05-20T09:00:00+02:00'}], 'gremium': {'name':
                'plenum', 'parlament': 'BT', 'wahlperiode': 20}, 'link': 'https://www.bundestag.de/sitzung/20240520', 'nummer':
                143, 'public': True, 'termin': '2024-05-20T09:00:00+02:00', 'titel': '143. Sitzung des Deutschen Bundestages',
                'tops': [{'nummer': 1, 'titel': 'Eröffnung der Sitzung'}, {'dokumente': [], 'nummer': 3, 'titel': 'Erste
                Beratung des von den Fraktionen SPD, BÜNDNIS 90/DIE GRÜNEN und FDP eingebrachten Entwurfs eines Gesetzes zur
                Änderung des Bundeswahlgesetzes', 'vorgang_id': ['123e4567-e89b-12d3-a456-426614174000']}]}

        Attributes:
            gremium (Gremium): Ein Gremium in dem Entscheidungen getroffen werden können. z.B: Ausschüsse, Plenum, Kabinett,
                Volk, ...
            nummer (int):
            public (bool):
            termin (datetime.datetime):  Example: 2024-03-15T10:00:00+00:00.
            tops (list[Top]):
            api_id (UUID | Unset): optional, here for future references. Is generated by the server.
            dokumente (list[Dokument | str] | Unset): Ankündigungen, TOPs und TOP änderungen bzw. Ergänzungen
            experten (list[Autor] | Unset): Optional: Liste von geladenen Experten. (macht aus der Sitzung eine Anhörung)
            link (str | Unset):
            titel (str | Unset): Titel wenn anwendbar. In den Ländern sind Themenüberschriften für AS üblich
            touched_by (list[TouchedByItem] | Unset): list of scraper uuids / key database ids that have touched this object
    """

    gremium: Gremium
    nummer: int
    public: bool
    termin: datetime.datetime
    tops: list[Top]
    api_id: UUID | Unset = UNSET
    dokumente: list[Dokument | str] | Unset = UNSET
    experten: list[Autor] | Unset = UNSET
    link: str | Unset = UNSET
    titel: str | Unset = UNSET
    touched_by: list[TouchedByItem] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.dokument import Dokument

        gremium = self.gremium.to_dict()

        nummer = self.nummer

        public = self.public

        termin = self.termin.isoformat()

        tops = []
        for tops_item_data in self.tops:
            tops_item = tops_item_data.to_dict()
            tops.append(tops_item)

        api_id: str | Unset = UNSET
        if not isinstance(self.api_id, Unset):
            api_id = str(self.api_id)

        dokumente: list[dict[str, Any] | str] | Unset = UNSET
        if not isinstance(self.dokumente, Unset):
            dokumente = []
            for dokumente_item_data in self.dokumente:
                dokumente_item: dict[str, Any] | str
                if isinstance(dokumente_item_data, Dokument):
                    dokumente_item = dokumente_item_data.to_dict()
                else:
                    dokumente_item = dokumente_item_data
                dokumente.append(dokumente_item)

        experten: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.experten, Unset):
            experten = []
            for experten_item_data in self.experten:
                experten_item = experten_item_data.to_dict()
                experten.append(experten_item)

        link = self.link

        titel = self.titel

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for componentsschemastouched_by_item_data in self.touched_by:
                componentsschemastouched_by_item = componentsschemastouched_by_item_data.to_dict()
                touched_by.append(componentsschemastouched_by_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "gremium": gremium,
                "nummer": nummer,
                "public": public,
                "termin": termin,
                "tops": tops,
            }
        )
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if dokumente is not UNSET:
            field_dict["dokumente"] = dokumente
        if experten is not UNSET:
            field_dict["experten"] = experten
        if link is not UNSET:
            field_dict["link"] = link
        if titel is not UNSET:
            field_dict["titel"] = titel
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.autor import Autor
        from ..models.dokument import Dokument
        from ..models.gremium import Gremium
        from ..models.top import Top
        from ..models.touched_by_item import TouchedByItem

        d = dict(src_dict)
        gremium = Gremium.from_dict(d.pop("gremium"))

        nummer = d.pop("nummer")

        public = d.pop("public")

        termin = isoparse(d.pop("termin"))

        tops = []
        _tops = d.pop("tops")
        for tops_item_data in _tops:
            tops_item = Top.from_dict(tops_item_data)

            tops.append(tops_item)

        _api_id = d.pop("api_id", UNSET)
        api_id: UUID | Unset
        if isinstance(_api_id, Unset):
            api_id = UNSET
        else:
            api_id = UUID(_api_id)

        _dokumente = d.pop("dokumente", UNSET)
        dokumente: list[Dokument | str] | Unset = UNSET
        if _dokumente is not UNSET:
            dokumente = []
            for dokumente_item_data in _dokumente:

                def _parse_dokumente_item(data: object) -> Dokument | str:
                    try:
                        if not isinstance(data, dict):
                            raise TypeError()
                        dokumente_item_type_0 = Dokument.from_dict(data)

                        return dokumente_item_type_0
                    except (TypeError, ValueError, AttributeError, KeyError):
                        pass
                    return cast(Dokument | str, data)

                dokumente_item = _parse_dokumente_item(dokumente_item_data)

                dokumente.append(dokumente_item)

        _experten = d.pop("experten", UNSET)
        experten: list[Autor] | Unset = UNSET
        if _experten is not UNSET:
            experten = []
            for experten_item_data in _experten:
                experten_item = Autor.from_dict(experten_item_data)

                experten.append(experten_item)

        link = d.pop("link", UNSET)

        titel = d.pop("titel", UNSET)

        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByItem] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for componentsschemastouched_by_item_data in _touched_by:
                componentsschemastouched_by_item = TouchedByItem.from_dict(componentsschemastouched_by_item_data)

                touched_by.append(componentsschemastouched_by_item)

        sitzung = cls(
            gremium=gremium,
            nummer=nummer,
            public=public,
            termin=termin,
            tops=tops,
            api_id=api_id,
            dokumente=dokumente,
            experten=experten,
            link=link,
            titel=titel,
            touched_by=touched_by,
        )

        sitzung.additional_properties = d
        return sitzung

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
