from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..models.stationstyp import Stationstyp
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.dokument import Dokument
    from ..models.gremium import Gremium
    from ..models.touched_by_item import TouchedByItem


T = TypeVar("T", bound="Station")


@_attrs_define
class Station:
    """Station ist in vielerlei hinsicht das Kernstück der API der Vorgänge. Jeder Vorgang besteht aus Stationen und die
    Stationen haben nur wenige verpflichtende Datenfelder.Für weitere Details, siehe die docs

        Example:
            {'additional_links': ['https://www.bundestag.de/mediathek/parlamentsfernsehen/aufzeichnungen/123456-123456'],
                'api_id': 'f1e2d3c4-b5a6-7890-abcd-1234567890cd', 'dokumente': [], 'gremium': {'name': 'plenum', 'parlament':
                'BT', 'wahlperiode': 20}, 'gremium_federf': False, 'link':
                'https://www.bundestag.de/dokumente/textarchiv/2024/erste-lesung-wahlrechtsreform', 'parlament': 'BT',
                'schlagworte': ['wahlrecht', 'reform', 'bundestag'], 'titel': 'Erste Lesung im Bundestag', 'trojanergefahr': 2,
                'typ': 'parl-vollvlsgn', 'zp_modifiziert': '2024-04-15T13:45:00+02:00', 'zp_start': '2024-04-15T10:00:00+02:00'}

        Attributes:
            dokumente (list[Dokument | str]):
            gremium (Gremium): Ein Gremium in dem Entscheidungen getroffen werden können. z.B: Ausschüsse, Plenum, Kabinett,
                Volk, ...
            typ (Stationstyp): Stationen, die ein Gesetz o.Ä. Vorgang in verschiedenen Ausformungen durchlaufen kann. Im
                Prinzip ist die Festlegung auf Prä / Postparlamentarisch arbiträr.
            zp_start (datetime.datetime): Datum an dem die erste Aktion dieser Station erstellt wurde, z.B. Erstes
                Sitzungsdatum des Ausschusses Example: 2024-01-01T00:00:00+00:00.
            additional_links (list[str] | Unset):
            api_id (UUID | Unset): optional, here for future references. Is generated by the server.
            gremium_federf (bool | Unset): Ist die Station eine Ausschussberatung gibt dieses Feld an ob es im
                Federführenden Ausschuss ist
            link (str | Unset): Link zu einer Übersichtsseite zu dieser Station. _NICHT_ zu einem Dokument (PDF)
            schlagworte (list[str] | Unset):
            stellungnahmen (list[Dokument | str] | Unset):
            titel (str | Unset): Optionaler Titel, falls die restlichen Daten keinen hinreichenden Rückschluss zulassen
            touched_by (list[TouchedByItem] | Unset): list of scraper uuids / key database ids that have touched this object
            trojanergefahr (int | Unset): Zahl im Intervall [1;10], die die Gefahr einer Schummelei angeben
            zp_modifiziert (datetime.datetime | Unset): Letztes relevantes Datum an dem die Station angefasst wurde z.B.:
                letzte sitzung oder nächste geplante sitzung Example: 2024-01-01T00:00:00+00:00.
    """

    dokumente: list[Dokument | str]
    gremium: Gremium
    typ: Stationstyp
    zp_start: datetime.datetime
    additional_links: list[str] | Unset = UNSET
    api_id: UUID | Unset = UNSET
    gremium_federf: bool | Unset = UNSET
    link: str | Unset = UNSET
    schlagworte: list[str] | Unset = UNSET
    stellungnahmen: list[Dokument | str] | Unset = UNSET
    titel: str | Unset = UNSET
    touched_by: list[TouchedByItem] | Unset = UNSET
    trojanergefahr: int | Unset = UNSET
    zp_modifiziert: datetime.datetime | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.dokument import Dokument

        dokumente = []
        for dokumente_item_data in self.dokumente:
            dokumente_item: dict[str, Any] | str
            if isinstance(dokumente_item_data, Dokument):
                dokumente_item = dokumente_item_data.to_dict()
            else:
                dokumente_item = dokumente_item_data
            dokumente.append(dokumente_item)

        gremium = self.gremium.to_dict()

        typ = self.typ.value

        zp_start = self.zp_start.isoformat()

        additional_links: list[str] | Unset = UNSET
        if not isinstance(self.additional_links, Unset):
            additional_links = self.additional_links

        api_id: str | Unset = UNSET
        if not isinstance(self.api_id, Unset):
            api_id = str(self.api_id)

        gremium_federf = self.gremium_federf

        link = self.link

        schlagworte: list[str] | Unset = UNSET
        if not isinstance(self.schlagworte, Unset):
            schlagworte = self.schlagworte

        stellungnahmen: list[dict[str, Any] | str] | Unset = UNSET
        if not isinstance(self.stellungnahmen, Unset):
            stellungnahmen = []
            for stellungnahmen_item_data in self.stellungnahmen:
                stellungnahmen_item: dict[str, Any] | str
                if isinstance(stellungnahmen_item_data, Dokument):
                    stellungnahmen_item = stellungnahmen_item_data.to_dict()
                else:
                    stellungnahmen_item = stellungnahmen_item_data
                stellungnahmen.append(stellungnahmen_item)

        titel = self.titel

        touched_by: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.touched_by, Unset):
            touched_by = []
            for componentsschemastouched_by_item_data in self.touched_by:
                componentsschemastouched_by_item = componentsschemastouched_by_item_data.to_dict()
                touched_by.append(componentsschemastouched_by_item)

        trojanergefahr = self.trojanergefahr

        zp_modifiziert: str | Unset = UNSET
        if not isinstance(self.zp_modifiziert, Unset):
            zp_modifiziert = self.zp_modifiziert.isoformat()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "dokumente": dokumente,
                "gremium": gremium,
                "typ": typ,
                "zp_start": zp_start,
            }
        )
        if additional_links is not UNSET:
            field_dict["additional_links"] = additional_links
        if api_id is not UNSET:
            field_dict["api_id"] = api_id
        if gremium_federf is not UNSET:
            field_dict["gremium_federf"] = gremium_federf
        if link is not UNSET:
            field_dict["link"] = link
        if schlagworte is not UNSET:
            field_dict["schlagworte"] = schlagworte
        if stellungnahmen is not UNSET:
            field_dict["stellungnahmen"] = stellungnahmen
        if titel is not UNSET:
            field_dict["titel"] = titel
        if touched_by is not UNSET:
            field_dict["touched_by"] = touched_by
        if trojanergefahr is not UNSET:
            field_dict["trojanergefahr"] = trojanergefahr
        if zp_modifiziert is not UNSET:
            field_dict["zp_modifiziert"] = zp_modifiziert

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.dokument import Dokument
        from ..models.gremium import Gremium
        from ..models.touched_by_item import TouchedByItem

        d = dict(src_dict)
        dokumente = []
        _dokumente = d.pop("dokumente")
        for dokumente_item_data in _dokumente:

            def _parse_dokumente_item(data: object) -> Dokument | str:
                try:
                    if not isinstance(data, dict):
                        raise TypeError()
                    dokumente_item_type_0 = Dokument.from_dict(data)

                    return dokumente_item_type_0
                except (TypeError, ValueError, AttributeError, KeyError):
                    pass
                return cast(Dokument | str, data)

            dokumente_item = _parse_dokumente_item(dokumente_item_data)

            dokumente.append(dokumente_item)

        gremium = Gremium.from_dict(d.pop("gremium"))

        typ = Stationstyp(d.pop("typ"))

        zp_start = isoparse(d.pop("zp_start"))

        additional_links = cast(list[str], d.pop("additional_links", UNSET))

        _api_id = d.pop("api_id", UNSET)
        api_id: UUID | Unset
        if isinstance(_api_id, Unset):
            api_id = UNSET
        else:
            api_id = UUID(_api_id)

        gremium_federf = d.pop("gremium_federf", UNSET)

        link = d.pop("link", UNSET)

        schlagworte = cast(list[str], d.pop("schlagworte", UNSET))

        _stellungnahmen = d.pop("stellungnahmen", UNSET)
        stellungnahmen: list[Dokument | str] | Unset = UNSET
        if _stellungnahmen is not UNSET:
            stellungnahmen = []
            for stellungnahmen_item_data in _stellungnahmen:

                def _parse_stellungnahmen_item(data: object) -> Dokument | str:
                    try:
                        if not isinstance(data, dict):
                            raise TypeError()
                        stellungnahmen_item_type_0 = Dokument.from_dict(data)

                        return stellungnahmen_item_type_0
                    except (TypeError, ValueError, AttributeError, KeyError):
                        pass
                    return cast(Dokument | str, data)

                stellungnahmen_item = _parse_stellungnahmen_item(stellungnahmen_item_data)

                stellungnahmen.append(stellungnahmen_item)

        titel = d.pop("titel", UNSET)

        _touched_by = d.pop("touched_by", UNSET)
        touched_by: list[TouchedByItem] | Unset = UNSET
        if _touched_by is not UNSET:
            touched_by = []
            for componentsschemastouched_by_item_data in _touched_by:
                componentsschemastouched_by_item = TouchedByItem.from_dict(componentsschemastouched_by_item_data)

                touched_by.append(componentsschemastouched_by_item)

        trojanergefahr = d.pop("trojanergefahr", UNSET)

        _zp_modifiziert = d.pop("zp_modifiziert", UNSET)
        zp_modifiziert: datetime.datetime | Unset
        if isinstance(_zp_modifiziert, Unset):
            zp_modifiziert = UNSET
        else:
            zp_modifiziert = isoparse(_zp_modifiziert)

        station = cls(
            dokumente=dokumente,
            gremium=gremium,
            typ=typ,
            zp_start=zp_start,
            additional_links=additional_links,
            api_id=api_id,
            gremium_federf=gremium_federf,
            link=link,
            schlagworte=schlagworte,
            stellungnahmen=stellungnahmen,
            titel=titel,
            touched_by=touched_by,
            trojanergefahr=trojanergefahr,
            zp_modifiziert=zp_modifiziert,
        )

        station.additional_properties = d
        return station

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
